"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, FileText, LockKeyhole, Search } from "lucide-react";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from "@/components/ui/alert-dialog";
import BulkProgress, { type BulkRun } from "./bulk-progress";
type Model = { id: string; name: string; task: string; enabled: boolean };
type Classification = { id: string; status: string; model: Model; result?: { label: string } };
type Paper = { id: string; title: string; conference: string; year: number; authors: string[]; word_count: number; characters: number; preview: string; decision: string; classifications: Classification[]; text?: string; abstract?: string; source_url?: string; };
const label: Record<string,string> = { human:"Human", ai:"AI generated", ai_assisted:"AI assisted", below_threshold:"Below AI threshold", ai_evidence:"AI evidence", uncertain:"Uncertain" };
export default function PaperLibrary({ models, defaultModel, api, open }: {models:Model[];defaultModel:string;api:(path:string,init?:RequestInit)=>Promise<any>;open:(id:string)=>void}) {
  const [papers,setPapers]=useState<Paper[]>([]), [paper,setPaper]=useState<Paper|null>(null);
  const [facets,setFacets]=useState<{conference:string;year:number;count:number}[]>([]);
  const [query,setQuery]=useState(''), [conference,setConference]=useState(''), [year,setYear]=useState('');
  const [model,setModel]=useState(defaultModel), [offset,setOffset]=useState(0), [total,setTotal]=useState(0);
  const [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const [classifiedBy,setClassifiedBy]=useState('');
  const [paperId,setPaperId]=useState('');
  const [run,setRun]=useState<BulkRun|null>(null), [bulkBusy,setBulkBusy]=useState(false), [stopOpen,setStopOpen]=useState(false);
  const [bulkLoaded,setBulkLoaded]=useState(false);
  const running=!!run&&['running','stopping'].includes(run.status);
  useEffect(()=>{let active=true; async function poll(){try{const d=await api('/v1/paper-runs');if(active){setRun(d.run);setBulkLoaded(true);}}catch(e){if(active)setError((e as Error).message);}} poll(); const timer=setInterval(poll,3000);return()=>{active=false;clearInterval(timer);};},[api]);
  async function startBulk(){setBulkBusy(true);setError('');try{const d=await api('/v1/paper-runs',{method:'POST',body:JSON.stringify({model_id:model,q:query,conference,year:year?Number(year):null,classified_by:classifiedBy})});setRun(d);}catch(e){setError((e as Error).message);}finally{setBulkBusy(false);}}
  async function stopBulk(mode:'finish'|'discard'){if(!run)return;setBulkBusy(true);setError('');try{setRun(await api('/v1/paper-runs/'+run.id+'/stop',{method:'POST',body:JSON.stringify({mode})}));setStopOpen(false);}catch(e){setError((e as Error).message);}finally{setBulkBusy(false);}}
  useEffect(()=>{ const route=()=>setPaperId(new URLSearchParams(window.location.search).get('paper')||''); route(); window.addEventListener('popstate',route); return ()=>window.removeEventListener('popstate',route); },[]);
  useEffect(()=>{ if(!model&&defaultModel)setModel(defaultModel); },[model,defaultModel]);
  useEffect(()=>{let active=true; setLoading(true);setError('');const timer=setTimeout(()=>{api(`/v1/papers?q=${encodeURIComponent(query)}&conference=${encodeURIComponent(conference)}${year?'&year='+year:''}&classified_by=${encodeURIComponent(classifiedBy)}&offset=${offset}`).then(d=>{if(active){setPapers(d.items);setTotal(d.total);setFacets(d.facets);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[api,query,conference,year,offset,classifiedBy,run?.counts.completed,run?.status]);
  useEffect(()=>{let active=true;setPaper(null);if(paperId){setBusy(true);setError('');api('/v1/papers/'+encodeURIComponent(paperId)).then(d=>{if(active)setPaper(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});}return()=>{active=false;};},[api,paperId]);
  function select(id:string){window.history.pushState({},'',id?'/papers?paper='+encodeURIComponent(id):'/papers');setPaperId(id);}
  async function compute(){if(!paper)return;setBusy(true);setError('');try{const d=await api('/v1/papers/'+encodeURIComponent(paper.id)+'/compute',{method:'POST',body:JSON.stringify({model_id:model})});open(d.scan.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const reason=paper ? !paper.characters ? 'This record has no archived paper text.' : paper.word_count<50 ? 'The archived text is too short to classify.' : paper.characters>500000||paper.word_count>100000 ? 'This full paper exceeds the current analysis size limit; its text remains available below.' : '' : '';
  return <section className="content-page paper-library">
    <div className="page-heading"><h1>Paper library</h1><span className="findings-storage"><LockKeyhole size={15}/> Read-only source archive</span></div>
    <p className="findings-intro">ReviewBench · Browse papers, compare model classifications and revisit saved reports.</p>
    {error&&<p className="findings-error" role="alert">{error}</p>}
    {paperId ? <>
      <button className="paper-back" onClick={()=>select('')}><ArrowLeft size={16}/> All papers</button>
      {!paper ? <p>{busy?'Loading paper…':'Paper unavailable'}</p> : <>
        <div className="paper-summary"><div className="paper-cohort">{paper.conference.toUpperCase()} {paper.year} · {paper.word_count.toLocaleString()} words · {paper.decision||'No decision listed'}</div><h2>{paper.title}</h2><p>{paper.authors.join(', ')}</p><a href={paper.source_url} target="_blank" rel="noreferrer">View original on OpenReview ↗</a></div>
        <div className="paper-classifications"><h3>Classifications</h3><p>Each model’s result is saved separately. Opening a report never reruns it.</p><div className="paper-classify-controls"><select aria-label="Paper classification model" value={model} onChange={e=>setModel(e.target.value)}><option value="" disabled>Choose model</option>{models.filter(m=>m.task==='text').map(m=><option key={m.id} value={m.id} disabled={!m.enabled}>{m.name}{!m.enabled?' (unavailable)':''}</option>)}</select><button className="primary" disabled={busy||!model||!!reason} onClick={compute}>{busy?'Opening…':'Compute / open result'}</button></div>{reason&&<p>{reason}</p>}
          <div className="paper-result-list">{paper.classifications.length?paper.classifications.map(c=><button key={c.id} onClick={()=>open(c.id)}><span>{c.model.name}</span><span className={'result-badge '+(c.result?.label||'')}>{c.result?label[c.result.label]||c.result.label:c.status}</span><ArrowRight size={16}/></button>):<p>No classifications yet. Choose a model to compute the first result.</p>}</div>
        </div>
        <details className="paper-source" open><summary><LockKeyhole size={15}/> Archived paper text · read-only</summary><p>Original OCR markdown, preserved as collected. Classification highlights appear in the report.</p><pre>{paper.text||'No paper text in this source record.'}</pre></details>
      </>}
    </> : <>
      <div className="history-toolbar findings-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search papers" placeholder="Search title, author or paper ID" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></div><select aria-label="Conference" value={conference} onChange={e=>{setConference(e.target.value);setOffset(0);}}><option value="">All conferences</option>{[...new Set(facets.map(f=>f.conference))].sort().map(c=><option key={c} value={c}>{c.toUpperCase()}</option>)}</select><select aria-label="Year" value={year} onChange={e=>{setYear(e.target.value);setOffset(0);}}><option value="">All years</option>{[...new Set(facets.map(f=>f.year))].sort((a,b)=>b-a).map(y=><option key={y} value={y}>{y}</option>)}</select></div>
      <div className="findings-toolbar paper-model-filter"><label htmlFor="classified-by">Classification</label><select id="classified-by" value={classifiedBy} onChange={e=>{setClassifiedBy(e.target.value);setOffset(0);}}><option value="">All papers</option><option value="any">Classified by any model</option><option value="not:any">Not classified by any model</option>{models.filter(m=>m.task==='text').map(m=><option key={m.id} value={m.id}>Classified by {m.name}</option>)}{models.filter(m=>m.task==='text').map(m=><option key={'not:'+m.id} value={'not:'+m.id}>Not classified by {m.name}</option>)}</select></div>
      <div className="paper-bulk-panel">
        <div className="paper-classify-controls"><label htmlFor="bulk-model">Bulk processing model</label><select id="bulk-model" value={model} disabled={running||bulkBusy} onChange={e=>setModel(e.target.value)}><option value="" disabled>Choose model</option>{models.filter(m=>m.task==='text').map(m=><option key={m.id} value={m.id} disabled={!m.enabled}>{m.name}{!m.enabled?' (unavailable)':''}</option>)}</select>
        {running?<button className="primary" onClick={()=>setStopOpen(true)} disabled={bulkBusy||run?.status==='stopping'}>{run?.status==='stopping'?'Finishing current paper…':'Stop bulk processing'}</button>:<button className="primary" onClick={startBulk} disabled={bulkBusy||!bulkLoaded||loading||!total||!models.some(m=>m.id===model&&m.enabled)}>{bulkBusy?'Starting…':'Start bulk processing'}</button>}</div>
        <p>Process unclassified papers for this model across all filtered pages, in the displayed order. Completed results are skipped. Papers run one at a time and are saved compressed.</p>
        {run&&<BulkProgress run={run} select={select} open={open}/>}
      </div>
      <AlertDialog open={stopOpen} onOpenChange={value=>{if(!bulkBusy)setStopOpen(value);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Stop bulk processing?</AlertDialogTitle><AlertDialogDescription>The remaining papers will not be started. Choose what happens to the paper currently being classified. Previously completed results will stay saved.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={bulkBusy}>Keep processing</AlertDialogCancel><button className="paper-stop-choice" disabled={bulkBusy} onClick={()=>stopBulk('discard')}>Discard current result and stop</button><button className="paper-stop-choice primary" disabled={bulkBusy} onClick={()=>stopBulk('finish')}>Finish current paper and stop</button></AlertDialogFooter><p className="muted">Discarding prevents the result from being saved. The model may take a moment to finish its current computation.</p></AlertDialogContent></AlertDialog>
      <p className="paper-library-count">{total.toLocaleString()} papers · Conference year and acceptance are not authorship labels.</p>
      {loading?<p>Loading papers…</p>:!papers.length?<p>No matching papers.</p>:<div className="findings-grid">{papers.map(p=><article className={`finding-card ${running&&run?.current?.paper_id===p.id?"paper-is-processing":""}`} key={p.id}>{running&&run?.current?.paper_id===p.id?<div className="paper-queue-badge processing"><span/> {run.current.status==='running'?'Processing now':'Waiting for model'}</div>:running&&run?.upcoming?.some(item=>item.paper_id===p.id)?<div className="paper-queue-badge upcoming">Up next · #{run.upcoming.findIndex(item=>item.paper_id===p.id)+1}</div>:null}<div className="finding-card-top"><FileText size={18}/><span>{p.conference.toUpperCase()} {p.year} · {p.word_count.toLocaleString()} words</span></div><h2><button onClick={()=>select(p.id)}>{p.title}</button></h2><p className="finding-preview">{p.preview||'Archived text unavailable'}</p><div className="finding-model">{p.classifications.length?p.classifications.map(c=><button key={c.id} onClick={()=>{window.history.replaceState({},'','/papers?paper='+encodeURIComponent(p.id));open(c.id);}}>{c.model.name} · {c.result?label[c.result.label]||c.result.label:c.status}</button>):<span>No saved classifications</span>}</div><div className="finding-footer"><span><LockKeyhole size={11}/> Read-only paper</span><button onClick={()=>select(p.id)}>View paper <ArrowRight size={16}/></button></div></article>)}</div>}
      <div className="findings-pagination"><span>{total?`${offset+1}–${Math.min(offset+20,total)} of ${total.toLocaleString()}`:'0 papers'}</span><button disabled={loading||!offset} onClick={()=>setOffset(offset-20)}>Previous</button><button disabled={loading||offset+20>=total} onClick={()=>setOffset(offset+20)}>Next</button></div>
      <p className="paper-attribution">Source: <a href="https://huggingface.co/datasets/Samarth0710/reviewbench" target="_blank" rel="noreferrer">Samarth0710/ReviewBench</a> · CC BY 4.0 · Original files, including peer reviews, are retained locally. This library classifies paper text.</p>
    </>}
  </section>;
}
