"use client";
import { useEffect, useState } from "react";
import { ChevronDown } from "lucide-react";
export type Segment = {start:number;end:number;score:number;label:string;raw_score?:number};
export default function SegmentExplorer({units,text,evidence,token,selected,onSelect}: {units:Segment[];text:string;evidence:boolean;token:boolean;selected:number|null;onSelect:(index:number|null,scroll?:boolean)=>void}) {
  const [filter,setFilter]=useState('all'),[limit,setLimit]=useState(40),[start,setStart]=useState(0);
  const chars=Array.from(text);
  const names:Record<string,string>={human:'Human written',ai:'AI',ai_assisted:'AI assisted',low_evidence:'Lower evidence',below_threshold:'Below AI threshold',ai_evidence:'AI evidence',uncertain:'Uncertain'};
  const labels=[...new Set(units.map(s=>s.label))];
  useEffect(()=>{if(selected!==null){setFilter('all');setStart(Math.floor(selected/40)*40);setLimit(40);requestAnimationFrame(()=>document.getElementById('segment-card-'+selected)?.scrollIntoView({block:'nearest',behavior:'instant'}));}},[selected]);
  useEffect(()=>{setLimit(40);setStart(0);setFilter('all');},[token,text]);
  const filtered=units.map((s,i)=>({s,i})).filter(({s})=>filter==='all'||s.label===filter);
  // Bound chart DOM size for full-paper token views; each plotted point selects its source segment.
  const step=Math.max(1,Math.ceil(units.length/400));
  const plotted=units.map((s,i)=>({s,i})).filter(({i})=>i%step===0);
  const unitName=token?'Token':evidence?'Sentence':'Segment';
  return <>
    <div className="analysis-card segment-map-card"><h3>{evidence?'AI EVIDENCE ACROSS DOCUMENT':'CLASSIFICATIONS ACROSS DOCUMENT'}</h3><p><strong>{units.filter(s=>s.label===(evidence?'ai_evidence':'ai')).length}</strong> of {units.length.toLocaleString()} {token?'tokens':evidence?'sentences':'segments'} {evidence?'above the reference threshold':'classified as AI'}</p>
      <div className="segment-map"><div className="segment-map-labels"><span>{evidence?'Strong':'AI'}</span><span>{evidence?'Evidence':'Assisted'}</span><span>{evidence?'Low':'Human'}</span></div><svg viewBox="0 0 400 86" preserveAspectRatio="none" role="group" aria-label="Classification across document">{[8,42,77].map(y=><line key={y} x1="0" x2="400" y1={y} y2={y} stroke="#e7e9eb"/>)}{plotted.map(({s,i},j)=>{const x=s.start/Math.max(1,chars.length)*400;const end=plotted[j+1]?.s.start??chars.length;const level=evidence?s.score:s.label==='ai'?1:s.label==='ai_assisted'?.5:0;const y=77-level*69;const color=evidence?'#e88750':s.label==='human'?'#236553':s.label==='ai_assisted'?'#dba336':'#de714a';return <g key={i} className="segment-plot-point" role="button" tabIndex={0} aria-label={`${unitName} ${i+1}: ${names[s.label]||s.label}`} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(i,true);}}} onClick={()=>onSelect(i,true)}><title>{unitName} {i+1}: {names[s.label]||s.label} · {s.score.toFixed(3)}</title><rect x={x} y={y} width={Math.max(1,(end-s.start)/Math.max(1,chars.length)*400)} height={86-y} fill={color} opacity={selected===i?.5:.23}/><rect x={x} y={y} width={Math.max(1,(end-s.start)/Math.max(1,chars.length)*400)} height="3" fill={color}/></g>;})}</svg></div><div className="segment-map-axis"><span>Document start</span><span>{text.trim().split(/\s+/u).filter(Boolean).length.toLocaleString()} words</span></div>
      {step>1&&<small className="muted">Chart shows a sampled overview. The list includes every {token?'token':'segment'}.</small>}
    </div>
    <div className="analysis-card segment-explorer"><div className="segment-explorer-heading"><h3>All {token?'tokens':evidence?'sentences':'segments'}</h3><select aria-label="Filter segments by classification" value={filter} onChange={e=>{setFilter(e.target.value);setLimit(40);setStart(0);}}><option value="all">All</option>{labels.map(label=><option key={label} value={label}>{names[label]||label}</option>)}</select></div>
      {!filtered.length&&<p>No matching segments.</p>}{filtered.slice(start,start+limit).map(({s,i})=>{const excerpt=chars.slice(s.start,s.end).join('');return <div id={'segment-card-'+i} key={i} className={'segment-accordion '+(selected===i?'selected':'')}><button className="segment-accordion-trigger" aria-expanded={selected===i} onClick={()=>onSelect(selected===i?null:i,true)}><span className={'segment-type-icon '+s.label}>▧</span><span className="segment-accordion-summary"><span><b>{names[s.label]||s.label}</b><small>{excerpt.trim().split(/\s+/u).filter(Boolean).length} words</small></span><span className="segment-excerpt">{excerpt}</span></span><ChevronDown size={14}/></button>{selected===i&&<div className="segment-accordion-body"><div className="segment-gauge" style={{background:`conic-gradient(from 270deg,#e77745 0deg ${s.score*180}deg,#e7ebe9 ${s.score*180}deg 180deg,transparent 180deg)`}}><div><strong>{(s.score*100).toFixed(1)}<small>/100</small></strong><span>{evidence?'AI evidence':'Model score'}</span></div></div><p>{evidence?'This passage shows '+(s.label==='ai_evidence'?'elevated':'lower')+' AI evidence.':`This model classified the passage as ${(names[s.label]||s.label).toLowerCase()}.`}</p><p className="muted">{evidence?'Local scores are exploratory evidence, not confidence or probabilities of authorship.':'Model scores are not percentages of AI-written words.'}</p><div className="segment-navigation"><button disabled={i===0} onClick={()=>onSelect(i-1,true)}>← Previous</button><span>{unitName} {i+1}</span><button disabled={i===units.length-1} onClick={()=>onSelect(i+1,true)}>Next →</button></div></div>}</div>;})}
      {start>0&&<button className="secondary" onClick={()=>setStart(Math.max(0,start-40))}>Previous segments</button>}{filtered.length>start+limit&&<button className="secondary" onClick={()=>setLimit(limit+40)}>Show more ({filtered.length-start-limit} remaining)</button>}
    </div>
  </>;
}
