"""Structured project ledger for Pangram, synthesized from all Claude Code sessions (Oct 3–6, 2026).

Times are stored in UTC ("YYYY-MM-DD HH:MM") and rendered in PDT (UTC-7) per the project rule.
"""
NOW = "2026-10-06 22:56"

SESSIONS = [
    {"id": "f0fb", "start": "2026-10-03 22:42", "end": "2026-10-04 00:17", "focus": "Paper Atlas redesign, mobile layout, search performance, Remote Control setup"},
    {"id": "2f2a", "start": "2026-10-04 00:21", "end": "2026-10-04 01:42", "focus": "State survey of Space/R2/H200; git repo creation and publication rules"},
    {"id": "9068", "start": "2026-10-03 22:39", "end": "2026-10-06 06:26", "focus": "Backbone evals, results page, overnight LoRA sweep, MoE runs, divergence guard, splice/LLM edit data, cross-model and held-out evals"},
    {"id": "d22e", "start": "2026-10-05 03:44", "end": "2026-10-05 03:58", "focus": "ROC/FPR explainer; Pangram report's AUROC/FPR inconsistency"},
    {"id": "67fb", "start": "2026-10-05 04:17", "end": "2026-10-05 04:38", "focus": "H200 storage, Space helper recovery out of /tmp"},
    {"id": "25a9", "start": "2026-10-05 04:33", "end": "2026-10-06 05:10", "focus": "Text extraction artifacts, positioned-clean-v2, MinerU, baseline omissions and LLM-judge hill-climb"},
    {"id": "3b26", "start": "2026-10-05 08:06", "end": "2026-10-06 06:32", "focus": "ICLR 2027 scoring at scale, 1%-FPR calibration, year diagnostic, OpenReview sample, Atlas publication and reader UX, sharing"},
    {"id": "33a3", "start": "2026-10-06 02:01", "end": "2026-10-06 06:27", "focus": "Soft n-gram / clause labeling test (Luna splitter, spaCy, synthetic edits)"},
]

GOALS = [
    ("Core research", "Detect AI-written text in research papers at document, sentence and token level while keeping false positives on human writing very low. The hardest case is catching one- or two-sentence AI edits inside otherwise human papers."),
    ("Training data", "Close the data gap that limits small-edit detection (only 2 of 24,000 stage-2 windows had an AI span under 200 characters), and grow trustworthy human paper text without teaching a formatting shortcut."),
    ("Text extraction", "Produce clean, positioned paper text from PDFs (the 'baseline': text-layer extraction plus cleanup), with figures, tables, garbled math and references removed and every omission marked."),
    ("Evaluation", "Report recall at a fixed 1% human false-positive rate, with ROC curves, held-out sets and enough seeds to beat noise, and test against writers other than the training generator."),
    ("Model and recipe", "Pick a backbone and LoRA recipe that is stable and cheap to iterate on; test whether larger models (MoE) or longer training help."),
    ("Paper Atlas", "Publish classifications on the Paper Atlas website with PDF overlays, calibration context and a reader that is pleasant to use, as a public version for collecting feedback before the announcement."),
    ("Infrastructure", "Run reliably across the HF Space (8×A100), the shared H200 node and Cloudflare R2 without losing work to restarts, quotas or rate limits."),
    ("Openness", "Keep the repo public-ready (no credentials, addresses, paper text or per-paper scores) and share work with a collaborator."),
]

FINDINGS = [
    ("Splice-trained models catch other writers' edits, less well", "At the deployment threshold the splice-trained 4B catches 63% of Haiku edits, 53% of Luna and 37–41% of Sonnet and Opus; the MoE without splices catches 22–33%.", "2026-10-06 06:54"),
    ("Current labels mark some human text as AI", "Clause-level soft labels found that 25% of the AI-labeled text in paragraph rewrites is near-verbatim human; clause labels beat sentence labels by +0.10 macro-F1 on synthetic edits.", "2026-10-06 12:37"),
    ("Training data was the main limit on small-edit detection", "Splicing single AI sentences into human passages lifted small-edit recall at 1% FPR from 0.25 to 0.58–0.63 (Qwen3.5-4B, 3 seeds). Recipe changes had stayed at 0.21–0.25.", "2026-10-06 05:52"),
    ("The learning-rate schedule caused the collapses, not the recipe", "The 5e-4 constant schedule without warmup collapsed around step 1,000 (4B and 9B); the same peak with warmup and cosine was fine. Recipe A (2e-4 cosine, 6% warmup) became the default.", "2026-10-05 13:22"),
    ("Longer training helps paper rewrites, not small edits", "Full-length 4B reached 0.89 on paper_v3 vs 0.77 at 20% length; small-edit recall stayed at 0.21–0.24.", "2026-10-05 19:47"),
    ("MoE: short run best, long run unstable", "The 20%-length Qwen3.6-35B-A3B scored all-edit 0.84 and small-edit 0.30; the full-length run at 2e-4 diverged, and the stable 1e-4 rerun was worse than the 20% run.", "2026-10-06 05:31"),
    ("No evidence of an extraction-artifact shortcut", "A shortcut here means a feature that predicts the label but is unrelated to authorship. Cleaning human text did not change FPR; adding extraction artifacts to AI text lowered recall only slightly (−0.05 with 10× the artifacts). 0 of 1,074 math sentences were flagged.", "2026-10-06 04:45"),
    ("Thresholds set on ordinary human papers do not hold on harder human text", "Cutoffs set on ordinary human papers flag 4.5–7% of human sentences next to edits and 16–29% of human paper_v3 sentences.", "2026-10-05 18:13"),
    ("Fast10 4B calibrated at 1% FPR", "Sentence threshold 0.0283 (held-out FPR 0.83%); catches 84% of one-sentence, 86% of two-sentence and 97% of paragraph edits. Rests on 215 pre-2023 papers; document-level threshold rests on 2.", "2026-10-06 00:10"),
    ("ICLR flag rates rise sharply by year", "Median share of sentences flagged: ≤2022 0.5%, 2023–2024 ≈0.7%, ICLR 2025 1.5–1.8%, ICLR 2026 14.5%, ICLR 2027 68%. Whether 2027 reflects AI use or a difference in submission format, or in topic and writing style over time, is unresolved.", "2026-10-06 01:55"),
    ("Baseline omissions now remove most noise", "On 100 random pages, noise left fell from 175 to 22 per 1k words (references now removed) with prose loss ~3 per 1k; clean pages rose from 16% to 45%.", "2026-10-06 04:29"),
    ("Bulk transfers must be bundled", "Per-file uploads stayed at ~8 MB/s regardless of parallelism; one stream reached 47 MB/s and four reached 88 MB/s. Bundles moved 27k files in 126 s.", "2026-10-06 03:15"),
]

# area, when (UTC), name, details, result, status
EXPERIMENTS = [
    ("Models", "2026-10-04 02:46", "Six-backbone comparison (fast10)", "ModernBERT, Ettin-1B, Qwen3.5-4B/9B, Gemma-4-12B, Qwen3.6-35B-A3B; five at 10% length", "Decoders beat encoders on public text by ~0.16 AUROC; paper AUROC tied (MoE 0.970). Sentence recall@1% FPR (1-sent/2-sent/para): MoE 32/46/95%, 9B 25/37/91%, 4B 18/18/44%.", "done"),
    ("Data", "2026-10-05 05:05", "Training-window audit", "24,000 stage-2 windows", "Only 2 windows contain an AI span under 200 characters.", "done"),
    ("Models", "2026-10-05 19:47", "Overnight LoRA sweep (arms A–L)", "Qwen3.5-4B/9B, 20% length, up to 3 seeds; A100 + H200", "A (2e-4 cosine) all-edit 0.770, small 0.249. 5e-4 constant collapses; standard AdamW (G) 0.515; short-span oversampling (L) no help. Small-edit recall stays at 0.21–0.25.", "done"),
    ("Evaluation", "2026-10-05 18:13", "Calibration transfer test", "16 checkpoints on calibration windows", "Cutoffs flag 0.2–1.6% of ordinary human papers but 4.5–7% of human sentences beside edits.", "done"),
    ("Evaluation", "2026-10-05 20:01", "Held-out 1% FPR, matched length", "cutoff fit on dev, applied to test", "Best now vs Oct 3: all-edit 0.78→0.80, small 0.22→0.26, paper_v3 0.59→0.87.", "done"),
    ("Models", "2026-10-05 21:39", "MoE 20% length (moe-A-s1)", "1 H200, 62 min", "All-edit 0.84, paragraph 0.98, small 0.30 (1 seed).", "done"),
    ("Models", "2026-10-06 02:25", "MoE full length at 2e-4", "2 H200s, data parallel", "Diverged near step 950 (loss peak 1.4); small-edit 0.14. ~3 h of H200 time lost.", "failed"),
    ("Infra", "2026-10-06 02:55", "Divergence guard replay", "all past H200 loss logs", "Flagged all 5 blown-up runs within 20–60 steps; 0 false alarms on 30 healthy runs.", "done"),
    ("Models", "2026-10-06 05:31", "MoE full length at 1e-4", "2 H200s, guard on", "Stable, but small-edit 0.16 dev / 0.21–0.23 test, worse than the 20% run.", "done"),
    ("Infra", "2026-10-06 05:31", "A100 MoE benchmark (FSDP2)", "2 A100s", "7.4 s/step at micro-batch 16; full run ≈5.1 h on 2 A100s vs 2.6 h on 2 H200s.", "done"),
    ("Evaluation", "2026-10-06 04:45", "Artifact-shortcut test", "4B and 9B; human text cleaned, AI text given extraction artifacts", "No FPR change from cleaning human text; adding artifacts to AI text lowers small-edit recall by up to 0.05.", "done"),
    ("Data", "2026-10-06 05:52", "Splice wave 1 (SPH, SPG)", "4B, 20% length, 3 seeds each", "Small-edit recall 0.249 → 0.582 (SPH) / 0.629 (SPG); costs: standalone rewrites 0.51 → 0.36 / 0.26, public AUROC (SPG) 0.911.", "done"),
    ("Data", "2026-10-06 05:21", "Luna LLM sentence edits v1", "5,370 calls, Flex tier", "5,000 accepted for $0.46; median span 131 characters.", "done"),
    ("Evaluation", "2026-10-06 06:38", "Cross-model eval (heterogeneous-ai-spans)", "both MoE runs", "Sentence AUROC 0.87–0.97 across six writers; corrected numbers on the comparison page.", "done"),
    ("Data", "2026-10-06 07:19", "Wave 2 (LLE, MIX, Arep)", "4B, 20% length, 1 seed each", "Lost in the 07:19 UTC Space restart before it was scored.", "failed"),
    ("Evaluation", "2026-10-06 06:54", "Multi-writer held-out eval", "1,185 Claude + 300 Luna edits on never-train papers", "Recall at the deployment threshold: 4B with splices Haiku 63%, Luna 53%, Sonnet/Opus 37–41%; MoE without splices 22–33%.", "done"),
    ("Data", "2026-10-06 12:37", "Clause-labeling test (soft labels)", "spaCy vs Luna splitters; synthetic v3 edits; relabel of 25,283 pairs", "Clauses beat sentences by +0.10 macro-F1 (CI +0.05 to +0.16); 25% of AI-labeled text in paragraph rewrites is near-verbatim human. 4B A/B pending approval.", "done"),
    ("Data", "2026-10-06 20:17", "Overnight data generation", "Claude subagents, ~120M tokens", "4,905 Claude sentence edits (strict check), 2,078 sections, 254 full papers, 1,228 paragraph edits; OpenAI-writer batch prepared for Codex.", "done"),
    ("Models", "2026-10-06 22:31", "River's one-factor sweep", "4B, 1 seed per setting", "No setting beat the reference (small-edit 0.26) beyond noise; River's MoE runs 0.22–0.30.", "done"),
    ("Data", "2026-10-05 23:40", "N-gram dashboard", "all human vs AI pools, hashing counter", "11 groups in under 2 min; soft-label explainer added.", "done"),
    ("Extraction", "2026-10-05 05:02", "Extraction artifact scan", "31,211 papers", "11 artifact classes (e.g. ICLR review line numbers in 100% of ICLR 2027).", "done"),
    ("Extraction", "2026-10-05 07:03", "positioned-clean-v2 + backfill", "41,004 + 1,414 ICLR 2027 papers", "Cleaned in ~28 min; 59.5M line-number words removed; 4 papers failed extraction.", "done"),
    ("Extraction", "2026-10-05 20:22", "MinerU2.5-Pro", "A100, vLLM", "First full run lost ~10 h to OOM; coverage check 98.3% median; judged too slow; kept a 300-paper, 9-page subset.", "stopped"),
    ("Extraction", "2026-10-06 04:29", "Baseline omissions hill-climb (v4→v6→math policy→references)", "Sonnet judges, 176 pages", "Noise left 175 → 22 per 1k; prose loss ~3 per 1k; clean pages 16% → 45%.", "done"),
    ("Classification", "2026-10-05 10:15", "Inference throughput benchmarks", "A100, 256 windows", "9B 9.7 → 11.3 win/s (merged LoRA); 4B 14.4 → 23.0 win/s (merged + torch.compile). Batch size had no effect.", "done"),
    ("Classification", "2026-10-05 23:30", "ICLR 2027 scoring (fast10 4B)", "42,419 papers; 1 GPU, then 8", "Done after a Space restart; 8-GPU claim queue finished the last 24k papers in ~2 h.", "done"),
    ("Evaluation", "2026-10-06 00:10", "1%-FPR calibration and ROC (fast10 4B)", "215 human papers, eval suite", "Threshold 0.0283, held-out FPR 0.83%; 0.1% threshold unstable; document level rests on 2 papers.", "done"),
    ("Evaluation", "2026-10-06 01:55", "Year diagnostic", "7,102 papers, 2023–2026 + downloads", "Flag rates flat through 2024, rising from 2025; ICLR 2026 14.5%, ICLR 2027 68%.", "done"),
    ("Extraction", "2026-10-06 01:12", "OpenReview ICLR 2024/2025 sample", "71 batch requests, Space extraction", "3,477 new papers extracted and cleaned with positioned-clean-v2.", "done"),
    ("Site", "2026-10-06 03:30", "Atlas publication", "42,418 detail files, catalogue update", "ICLR 2027 classified as 'Qwen3.5-4B · Experimental'; Calibration page live.", "done"),
    ("Infra", "2026-10-06 07:00", "Training-storage cleanup and index", "owner-approved Tier 1 + Tier 3", "Bucket 1,074 → 652 GB: removed orphaned partial uploads (72 GB), duplicated ICLR round-2/3 PDFs (77 GB) and Oct 1–3 experiment weights (273 GB); every folder indexed in workspace/README.md.", "done"),
    ("Site", "2026-10-04 00:17", "Atlas redesign and performance", "Cloudflare Workers", "Redesign and mobile fixes shipped; live search still 2.5–5 s.", "partial"),
]

# label, when (UTC), session, detail
ACCEPTED = [
    ("Git repo, public-ready but private until announcement; scrub from first commit", "2026-10-04 01:36", "2f2a"),
    ("Sentence-level ROC curves on the results page", "2026-10-05 04:08", "9068"),
    ("Monitor runs every 15 min; one-minute sanity check after launch", "2026-10-05 18:55", "25a9"),
    ("Pause runs immediately to free A100 GPUs 2 and 3", "2026-10-05 07:39", "9068"),
    ("Stride 510 and merged LoRA for ICLR scoring", "2026-10-05 10:05", "3b26"),
    ("Parallelize ICLR scoring across all 8 GPUs with an interruptible queue", "2026-10-05 21:20", "3b26"),
    ("Flag at 1% human FPR with ROC curves as standard practice", "2026-10-06 00:05", "3b26"),
    ("Raw probabilities plus calibration metadata instead of rescaled scores", "2026-10-06 02:55", "3b26"),
    ("RAM disk (/dev/shm) as H200 storage for re-downloadable files", "2026-10-06 00:19", "9068"),
    ("Rerun MoE at LR 1e-4 with divergence guard; auto-rollback option", "2026-10-06 02:43", "9068"),
    ("Data priorities: splice edits, artifact-shortcut test, LLM sentence edits", "2026-10-06 04:07", "9068"),
    ("Math policy for omissions; remove references entirely; span-anchored judge metrics", "2026-10-06 03:22", "25a9"),
    ("Bundle bulk transfers (your idea); downloads run on the Space", "2026-10-06 03:20", "3b26"),
    ("Checkpoint policy: one resumable checkpoint during a run, final weights after scoring", "2026-10-05 20:58", "9068"),
]

OVERRIDDEN = [
    ("Claude recommended keeping ICLR 2027 flags private until drift was understood", "You published them publicly as 'Experimental' to iterate on the UX", "2026-10-06 02:35", "3b26"),
    ("Claude suggested rescaling scores to the human-FPR scale", "You questioned it as possibly post-hoc; raw scores were kept", "2026-10-06 02:55", "3b26"),
    ("Claude flagged that pushing to a public repo publishes before the announcement", "You pushed the branch woog97/workbench to rain-1/pangram-at-home", "2026-10-06 06:20", "3b26"),
    ("Claude argued against a VLM parser (MinerU) as a text source", "You ran MinerU anyway, then judged it too slow and cut it to 300 papers", "2026-10-05 06:53", "25a9"),
    ("Claude proposed re-adding the 9B curve on the baseline recipe", "\"i dont trust u, i trust john schulman\": stayed on LoRA Without Regret (which later collapsed on its schedule)", "2026-10-05 07:23", "9068"),
    ("Claude wanted 3 seeds for wave 2", "You cut to 1 seed to get the comparison artifact sooner", "2026-10-06 06:09", "9068"),
    ("Claude proposed an API budget for the multi-writer eval set", "You chose Claude subagents on your account", "2026-10-06 05:53", "9068"),
    ("Claude proposed exact 10%-length runs to separate length from recipe", "You chose a 20% MoE run instead", "2026-10-05 20:18", "9068"),
    ("Claude recommended pausing or shrinking the Space to save cost", "GPUs are a community grant; only storage costs money", "2026-10-05 20:48", "9068"),
    ("Claude suggested more GPUs for MinerU", "You cut scope to 9 pages × 300 papers", "2026-10-05 20:19", "25a9"),
    ("Claude deleted MoE base weights after a run", "You objected; weights restored; delete base weights only on explicit request", "2026-10-05 21:56", "9068"),
    ("Claude launched a full classification run before benchmarking", "You asked to benchmark small batches first", "2026-10-05 09:00", "3b26"),
]

# Flags Claude raised that got no answer and are still relevant. severity: high / medium / low
IGNORED = [
    ("Publishing per-paper AI scores, PDF redistribution licensing, unverified-permission passages, open weights", "Raised before the repo existed; per-paper ICLR 2027 scores are now public on the Atlas.", "2026-10-04 01:29", "2f2a", "high"),
    ("Project name close to Pangram Labs; workbench imitates their dashboard and brand", "Matters before the announcement.", "2026-10-04 01:41", "2f2a", "high"),
    ("Is the AI-side text run through the same omission step?", "If only human text gets markers, the model can learn a formatting shortcut.", "2026-10-06 03:22", "25a9", "high"),
    ("Credential rotation: the Jupyter token (Oct 5, 00:44 PDT) and HF token (Oct 5, 17:50 PDT) were printed in session output", "Rotation never confirmed.", "2026-10-06 00:50", "3b26", "high"),
    ("ICLR 2027 drift checks: read top-flagged sentences; compare ICLR 2026 submission versions", "Needed before treating 68% as AI use.", "2026-10-06 01:55", "3b26", "high"),
    ("Add to the human calibration set from ~20k 2019–2022 Atlas PDFs", "Document-level threshold rests on 2 papers; 0.1% threshold unstable.", "2026-10-06 02:40", "3b26", "medium"),
    ("PyMuPDF AGPL licence risk for the omissions code", "Raised twice.", "2026-10-06 00:03", "25a9", "medium"),
    ("Pre-2022 arXiv LaTeX / PMC as the top human data source", "Proposed a 10k-paper first batch.", "2026-10-06 05:11", "9068", "medium"),
    ("Build the --fsdp A100 MoE training path", "Benchmark done; ~2 h of work.", "2026-10-06 05:32", "9068", "medium"),
    ("fp32 master weights if instability persists", "Trainable weights are BF16 without an fp32 copy.", "2026-10-05 07:24", "9068", "low"),
    ("Manual review of omission pages in the review dashboard", "No verdicts saved yet; 'good enough' decision pending.", "2026-10-06 04:08", "25a9", "medium"),
    ("Do paired passages label the whole rewritten span as AI? Compare to soft labels", "data.py not checked.", "2026-10-06 02:03", "33a3", "medium"),
    ("What is the n-gram work for: exploration or detector features?", "", "2026-10-05 23:45", "9068", "low"),
    ("Storage cleanup of current runs: prune non-selected checkpoints (~70–80 GB), 9.3 GB on the H200, 68 GB MoE copy in Space /tmp", "Oct 6 cleanup handled the archive; these were not approved.", "2026-10-06 07:00", "3b26", "low"),
    ("Run one agent at a time on shared files and GPUs", "Parallel sessions interfered with each other several times (duplicate GPU runs, outdated CLAUDE.md, uncommitted files from several sessions in one working tree).", "2026-10-03 23:54", "f0fb", "medium"),
    ("Calibrated colour bands per model in the reader and list", "Raw-score bands colour most flagged sentences red and some green.", "2026-10-06 03:35", "3b26", "low"),
    ("Retry the ICLR round-3 loader (stale lock on the Space)", "Likely superseded by the complete ICLR 2027 dataset; confirm and close.", "2026-10-04 00:34", "9068", "low"),
]

# title, area, last touched (UTC), state, next step, priority
THREADS = [
    ("Is ICLR 2027's 68% real AI use?", "Evaluation", "2026-10-06 01:55", "open", "Read top-flagged sentences in 20 papers; score ICLR 2026 submission versions (~20 batch requests).", "high"),
    ("Train and test the new data mix (wave 2 was lost)", "Data", "2026-10-06 19:29", "open", "Build the table-2 mix, train 4B × 3 seeds vs SPG, score per writer.", "high"),
    ("Soft-label A/B (clause labels)", "Data", "2026-10-06 12:37", "waiting on you", "Approve 2 A100s for 4B original vs soft labels, 3 seeds each.", "high"),
    ("OpenAI-writer data via Codex", "Data", "2026-10-06 20:07", "waiting on you", "Start a Codex conversation with research/openai-writer-handoff-20261006 (D 1,000 items, E 420).", "medium"),
    ("Commit and push the overnight code", "Infra", "2026-10-06 22:31", "waiting on you", "Branch overnight-20261006 (f479f32) is not pushed; later changes are uncommitted.", "medium"),
    ("Same omission treatment for AI-side text", "Extraction", "2026-10-06 03:22", "open", "Decide whether AI text goes through the omission step before using omitted human text in training.", "high"),
    ("Apply references removal and omissions to the corpus", "Extraction", "2026-10-06 04:29", "open", "Regenerate clean datasets; run the full-corpus omission pass (~2 h CPU).", "medium"),
    ("Omission regressions and leaks", "Extraction", "2026-10-06 04:29", "open", "Fix the small-caps heading regression, pseudocode-as-math losses, table cell leaks, caption cut.", "medium"),
    ("Code-block and algorithm policy", "Extraction", "2026-10-06 02:31", "open", "Decide whether code listings get a ⟦code omitted⟧ marker.", "low"),
    ("Manual 'good enough' review of omissions", "Extraction", "2026-10-06 05:06", "waiting on you", "Save verdicts on ~10 random pages in the review dashboard.", "medium"),
    ("Revisit overnight A vs B conclusions", "Models", "2026-10-06 02:55", "open", "Re-read arm comparisons excluding diverged 5e-4 seeds.", "medium"),
    ("Add human calibration data", "Evaluation", "2026-10-06 02:40", "open", "Extract ~2,000 of the 2019–2022 Atlas PDFs; recalibrate document and 0.1% thresholds.", "medium"),
    ("False positives next to AI spans", "Evaluation", "2026-10-06 06:05", "open", "Measure how often human sentences are flagged at each distance from an AI span.", "medium"),
    ("FSDP MoE training on A100s", "Infra", "2026-10-06 05:32", "waiting on you", "Approve building --fsdp (8-bit optimizer wrapper, sharded save and validation).", "low"),
    ("Exact 10%-length runs", "Models", "2026-10-05 20:01", "stale", "Run if length vs recipe still matters; otherwise close.", "low"),
    ("Ettin sentence curves and MoE vs 9B bootstrap", "Evaluation", "2026-10-05 04:17", "stale", "Low value now; close unless needed for a write-up.", "low"),
    ("9B scoring of ICLR 2027", "Classification", "2026-10-05 10:20", "deferred", "You skipped it; revisit with the splice-trained model instead of fast10.", "low"),
    ("Calibrated colour bands in the reader", "Site", "2026-10-06 03:35", "open", "Per-model bands and an FPR-labelled threshold slider.", "medium"),
    ("Atlas search latency", "Site", "2026-10-04 00:17", "stale", "Stream the 80 MB index or move search out of the Worker; live search is 2.5–5 s.", "medium"),
    ("Commit and consolidate code", "Infra", "2026-10-06 06:20", "open", "Land today's work on woog97/paingram main; one pipeline tool, shared helpers, tests.", "medium"),
    ("Credential rotation", "Infra", "2026-10-06 00:50", "waiting on you", "Rotate the HF token and the Jupyter token.", "high"),
    ("Storage cleanup: remaining items", "Infra", "2026-10-06 07:00", "waiting on you", "Bucket cleaned on Oct 6 (1,074 → 652 GB, index at workspace/README.md). Still open: pruning checkpoints of current runs (not approved), 9.3 GB on the H200, 68 GB MoE copy in Space /tmp.", "low"),
    ("Calibration-window overlap with the eval suite", "Evaluation", "2026-10-04 01:31", "stale", "Probably handled by calibration-exclude-papers.json (Oct 5); verify and close.", "low"),
    ("Small-caps stray space and NeurIPS checklist spot-check", "Extraction", "2026-10-05 19:24", "stale", "Fix 'LOW -RANK' joins; spot-check ~18.7k removed checklist words.", "low"),
]

# category, title, when (UTC), cost, fix, recurrences
ISSUES = [
    ("Storage", "Space restarts wiped /tmp", "2026-10-06 21:36", "Sweep checkpoints, Space tools and wave 2 lost; ~75 min of baseline reruns; classification runtime rebuilt", "Persist daemon mirrors /tmp to /data every 5 min; restart watcher; vendored packages on /data", 4),
    ("Storage", "Shared H200 quota exhausted", "2026-10-05 23:39", "curve-9b-B killed at 36%; moe-A-full crashed mid-run (~45 min)", "RAM disk for re-downloadable files; measure real free space before large writes", 2),
    ("Training", "Loss divergence detected late", "2026-10-06 02:43", "~3 h of H200 time on a damaged MoE run; detection ~1.5 h late; pre-spike weights lost", "Divergence guard, rolling snapshots, loss-aware health checks, auto-rollback", 5),
    ("Transfer", "Per-file transfers and polling hit rate limits", "2026-10-05 07:15", "~30 min Space 429 lockout; ~25 min slow R2 uploads; 18 GB downloaded to the Mac and 19 GB uploaded again instead of transferring directly", "500 requests / 5 min budget; bundle everything; run downloads on the Space", 3),
    ("Extraction", "MinerU settings changed after calibration", "2026-10-05 18:34", "~10 h of failed GPU work (21,001 OOM errors)", "Never change settings between calibration and the full run; failure-rate breaker", 1),
    ("Environment", "Missing tools after restarts", "2026-10-06 01:00", "Repeated stalls: poppler, tesseract, pypdf, Pillow, nvcc, OpenCV, transformers versions, W&B key, HF token", "Pinned micromamba envs, vendored packages, keys passed via env at launch", 8),
    ("Security", "Credentials printed in session output", "2026-10-06 00:50", "Jupyter token and HF token exposed in transcripts", "Redaction and compile-check-before-send rules; rotation still pending", 2),
    ("Analysis", "Wrong claims later corrected", "2026-10-06 04:32", "Misleading numbers on the results page and in CLAUDE.md for hours", "Corrected: edit-catch rate, MinerU text loss, coverage counts, '8–12 pt seed noise', cause of slow uploads", 6),
    ("Coordination", "Parallel sessions interfered with each other", "2026-10-05 21:10", "Duplicate GPU runs, misread GPU assignments, outdated CLAUDE.md reads, uncommitted files from several sessions in one working tree", "Session handoff messages; per-thread scope; separate git index for commits", 4),
    ("Tooling", "Blocked tool calls and permission prompts", "2026-10-06 06:20", "Blocked publishes, deletes, pushes and launches needed manual approval; sleep blocked; browser extension unavailable", "Manual mode for approvals; background watchers; headless browser via puppeteer", 9),
    ("Process", "Jobs launched before checks were in place", "2026-10-05 23:45", "Unbenchmarked launch; prototype without a progress counter; watchers that only checked completion", "Benchmark first; 1/2/4/…/60-min backoff checks; loss-aware monitoring", 3),
    ("Process", "Annotation effort abandoned", "2026-10-06 05:03", "300-sentence gold set stopped after ~15", "Synthetic known-truth edits instead", 1),
    ("Site", "Reader layout bugs", "2026-10-06 03:40", "Page jumps broken, highlights hidden on Discover, page-strip marks collapsed", "Bounded reader height, full reader on Discover, gradient strips, follow-reading panel", 3),
]

RULES = [
    ("Communication", "Keep answers short and direct; when asked for status, give status, not results."),
    ("Communication", "Report times in PDT."),
    ("Evaluation", "Flag at 1% human FPR with ROC curves; never present 0.5-cutoff labels as classifications."),
    ("Evaluation", "Papers from 2022 or earlier are human-written; don't argue it."),
    ("Evaluation", "Distrust aggregates; validate visually and with frozen, random held-out sets."),
    ("Training", "Follow LoRA Without Regret where possible; present evidence when data disagrees."),
    ("Training", "BF16 for inference, trainable weights and checkpoints; no fp32 copies."),
    ("Training", "During a run keep one resumable checkpoint; after scoring keep final weights only; delete base weights only on explicit request; never delete the MoE base weights."),
    ("Operations", "Benchmark throughput on small batches before launching large runs."),
    ("Operations", "Check every job at 1, 2, 4, 8, 16, 32 minutes, then hourly; watch loss, not just liveness; fix and reset on stalls."),
    ("Operations", "Bundle bulk transfers; stay under 500 HF requests per 5 minutes; run downloads on the Space."),
    ("Operations", "Download new model weights only on the Space (exceptions recorded in AGENTS.md); use /dev/shm on the H200 for re-downloadable files."),
    ("Operations", "Ask before deleting anything on the Space or launching on shared hardware beyond what was agreed."),
    ("Security", "Never print or commit credentials; compile-check credential-bearing remote code; keep helpers and keys in ~/.config/pangram."),
    ("Openness", "Commits must be public-ready: no credentials, infrastructure addresses, third-party paper text, per-paper scores or brand assets."),
    ("Data", "OCR only as a fallback for garbled pages; omit figure text and keep captions; mark every omission; remove references from classification input."),
    ("Data", "LLM labelling on Luna (Flex tier) with spend caps and a pilot first; eval edits via Claude subagents."),
    ("Data", "No direct OpenAI API generation; OpenAI-model data goes through a written handoff to a new Codex conversation."),
    ("Collaboration", "River (collaborator) runs jobs on the same hardware: anything not started by you or your sessions is River's; don't stop, change or delete it without asking."),
    ("Operations", "Space outputs go to /data (persist daemon); don't change Space hardware or settings during live runs without asking."),
    ("Communication", "Answer the actual question plainly; don't be pedantic. Write literally."),
]

LINKS = [
    ("Paper Atlas (live)", "https://pangram-paper-atlas.woog09.workers.dev"),
    ("Calibration page", "https://pangram-paper-atlas.woog09.workers.dev/?view=calibration"),
    ("Backbone and sweep results", "https://claude.ai/artifact/QJJUjcHwHNmXuqFNKX28QQ"),
    ("Model comparison (latest)", "https://claude.ai/artifact/1Wey5VmYi8yN2gYgZJ7Zjy"),
    ("Fast10 4B calibration", "https://claude.ai/artifact/4FNSVgD1vH8i87w4XYpq7D"),
    ("Omissions review dashboard", "https://claude.ai/artifact/5KBFUaGaYrmcisSiSNUqxc"),
    ("Text layer vs MinerU", "https://claude.ai/artifact/WJFxShnEYkfVkSer1d82cb"),
    ("N-gram dashboard", "https://claude.ai/artifact/WPLSuRnVBwgjoS9uHm5GcP"),
    ("Clause annotation page", "https://claude.ai/artifact/YVG8QfNMXZBKEU6rdZsQna"),
    ("Shared branch", "https://github.com/rain-1/pangram-at-home/tree/woog97/workbench"),
    ("Project ledger page", "https://claude.ai/artifact/VDHHWuQhGUPNcxFvwJRSRn"),
]

# What each owner item needs: a decision (policy choice), an approval (Claude can do it once approved), or an action (only you can do it)
OWNER_TYPE = {
    "Publishing per-paper AI scores": "decision",
    "Project name close to Pangram Labs": "decision",
    "Is the AI-side text run through the same omission step?": "decision",
    "Credential rotation": "action",
    "ICLR 2027 drift checks": "approval",
    "Manual 'good enough' review of omissions": "action",
    "FSDP MoE training on A100s": "approval",
    "Storage cleanup": "approval",
}
def owner_type(text):
    return next((v for k, v in OWNER_TYPE.items() if text.startswith(k)), "decision")

OWNER_TYPE.update({
    "Soft-label A/B": "approval",
    "OpenAI-writer data via Codex": "action",
    "Commit and push the overnight code": "approval",
})

# Priorities (assessment as of Oct 6, 15:56 PDT).
PRIORITY_NOTE = ("\"Your time\" is active time in conversation: for each message you sent, the gap to your next message in that session, capped at 10 minutes "
                 "(longer gaps count as away). Messages were assigned to topics by session, time window and keywords, and spot-checked, so hours are approximate (about ±20%). "
                 "Total: ~27.6 h of active time over 336 chat rounds (a round is one message from you and Claude's reply to it), Oct 3–6.")
# topic, your hours, chat rounds, payoff
ENGAGEMENT = [
    ("Space restarts, storage and monitoring", 3.4, 50, "overhead"),
    ("Data generation (splices, LLM edits)", 3.2, 47, "high"),
    ("MinerU", 3.1, 32, "low"),
    ("ICLR scoring, calibration and year diagnostic", 2.5, 22, "mixed"),
    ("MoE runs", 2.2, 32, "low"),
    ("Omissions (extraction tuning)", 1.9, 19, "mixed"),
    ("Training sweeps (recipe, LR)", 1.9, 27, "low"),
    ("Evals, metrics and results pages", 1.6, 18, "high"),
    ("Atlas publishing and reader UX", 1.5, 18, "mixed"),
    ("Clause labeling (soft labels)", 1.5, 13, "promising"),
    ("Project ledger, repo and sharing", 1.2, 20, "overhead"),
    ("Atlas site redesign (Oct 3)", 0.9, 7, "mixed"),
    ("N-gram dashboard", 0.8, 9, "low"),
    ("Repo setup and docs", 0.7, 9, "overhead"),
    ("Text extraction and cleanup", 0.7, 5, "high"),
    ("Claude Code setup", 0.3, 6, "overhead"),
]
# work, your time, compute, outcome, assessment
LOW_PAYOFF = [
    ("Space restarts, storage and monitoring", "3.4 h active, 50 chat rounds", "4 restarts in 3 days; checkpoints and wave 2 lost", "Persistence to /data, a restart watcher, the storage index and monitoring rules now exist.", "Reactive work and the largest share of your time. The new tools should reduce it; the restarts themselves are unexplained."),
    ("MinerU PDF extraction", "3.1 h active, 32 chat rounds", "~10 GPU hours lost to out-of-memory errors, ~1 h setup", "Judged too slow and dropped; a 300-paper subset kept.", "Your largest block of time with the least to show for it."),
    ("ICLR scoring and Atlas publishing of the fast10 4B", "4.0 h active, 40 chat rounds (2.5 + 1.5)", "~8 GPU hours, 15 GB of uploads", "ICLR 2027 classified on the site; reader fixes; Calibration page.", "The reader and calibration work carries over. The scores come from a model the splice models outperform, and the 68% figure is unvalidated."),
    ("MoE runs and scaling", "2.2 h active, 32 chat rounds", "~10 H200 hours (two full runs, benchmarks)", "Full-length runs overfit (best epoch 0) and scored below the 20%-length run.", "Low payoff; the divergence guard built during this work is still in use."),
    ("Recipe and hyperparameter sweeps", "1.9 h active, 27 chat rounds", "~12 h on 4 A100s + 3 H200s, plus River's sweep", "Small-edit recall stayed at 0.21–0.26 for every setting, in both sweeps.", "Useful negative result, larger than needed: the data audit had already pointed to data."),
    ("Omission-step tuning", "1.9 h active, 19 chat rounds", "~8 h of Claude session, ~5M subagent tokens", "Noise left fell from 175 to 22 per 1k words; references removal.", "Partly useful; later iterations changed little, and the AI-side policy is still undecided."),
    ("N-gram dashboard", "0.8 h active, 9 chat rounds", "minutes of CPU", "Exploratory statistics; their use was never decided.", "Low payoff."),
]
STOP = [
    ("More hyperparameter or recipe sweeps", "Two independent sweeps (ours and River's) found nothing that beats the reference recipe beyond noise. Data changes moved small-edit recall from 0.25 to ~0.6."),
    ("Full-length MoE runs and the FSDP A100 path", "Full-length MoE overfit (best epoch 0) and scored below the 20%-length run. The one MoE run worth doing is a short run on the chosen data mix, after item 1."),
    ("Further omission tuning (table leaks, pseudocode, captions)", "Decide item 4 first; until then more tuning may not affect training."),
    ("More site work on the current 4B scores", "Rescore ICLR 2027 with the chosen model first (item 6)."),
    ("N-gram dashboard follow-ups", "No decision depends on it."),
]
# title, tldr, your time, compute/wall, depends, steps, risks, done
TODAY = [
    ("Train and test the new small-edit data mix",
     "Wave 2 was lost in the 07:19 UTC restart before it was scored. Build the planned mix from the new data pool, train 4B × 3 seeds against SPG, and run the soft-label A/B at the same time.",
     "~20 min: approve the mix and GPU use; agree GPUs with River",
     "~3–4 h wall: 4B at 20% length takes ~75–90 min per run on an A100 (seeds in parallel) plus ~20 min scoring; the soft-label A/B (6 runs) runs on other GPUs at the same time",
     "Free A100s (River's runs); persistence to /data running",
     ["Agree with River which A100s are free.",
      "Build the 'table 2' mix (small edits 35%, human paper 25%, paragraph 12%, fully AI 10%, generic human 7%, sections 6%, GRADTEX 5%) from the pool: ~16,000 small edits fit a 510-token window (splices ~7,760, Luna ~4,400, Claude ~4,100 after the strict check). About 1 h of work. Drop the 22 never-train rows.",
      "Train 4B, 20% length, recipe A, 3 seeds; compare with SPG (rerun SPG if its checkpoints are not in the bucket).",
      "Run the soft-label A/B (original vs clause soft labels, 3 seeds each), which the clause-labeling session has prepared.",
      "Score dev/test and the strict multi-writer held-out set (871 Claude rows + 300 Luna); report recall per writer at a held-out 1% FPR with the spread across seeds.",
      "Choose the mix; then one confirmation run at full length or on 9B (~4–5 h)."],
     ["Another restart: write outputs to /data (persist daemon).",
      "Splices and some evaluation edits both come from Luna: decide on the Sonnet, Opus and Haiku columns.",
      "Single-seed noise is ±0.03–0.06; the held-out test sets are small (±0.07 on 150 sentences)."],
     "A chosen mix with ≥3 seeds per finalist, per-writer recall at 1% FPR, and the regressions (standalone rewrites, public AUROC) listed."),
    ("Check whether ICLR 2027's 68% is real",
     "Read the top-flagged sentences in ~20 papers and score ICLR 2026 submission versions before more site work.",
     "~45 min: read flagged sentences in ~20 papers (only you can judge these)",
     "~3–4 h wall, mostly automated",
     "OpenReview quota (140 requests/hour, run on the Space); ~30 GPU-minutes",
     ["Break flags down by section from the existing sentence scores (~30 min CPU). References are still in the classification input, so check whether references or template text drive the flags.",
      "Build a reading page: top-flagged sentences in context for 20 papers with high, middle and low flag shares (~1 h).",
      "Version control: download ~1,000 ICLR 2026 rejected submissions (their PDFs are submission versions, the same format as ICLR 2027): ~20 batch requests, extraction and cleanup ~15 min, scoring ~15 min.",
      "Second model: score a 1,000-paper ICLR 2027 subset with the best splice-trained model.",
      "Write the verdict with the evidence on the Calibration page."],
     ["There is no human ground truth for 2027 papers: this can rule out format and section causes but cannot prove AI use."],
     "A written verdict with the section breakdown, the ICLR 2026 submission control and second-model agreement."),
    ("Add human calibration data",
     "Extract part of the ~20k 2019–2022 PDFs already in R2; the document-level threshold rests on 2 papers.",
     "~10 min: approve exporting PDFs from R2",
     "~half a day wall: ~1 h engineering, ~1 h compute, ~1 h analysis",
     "Read access to the Atlas R2 bucket from the Space (a temporary token-gated export endpoint, like /bundle in reverse)",
     ["Select ~2,000 papers stratified by venue and year.",
      "Export them to the Space as tar bundles (~10 GB).",
      "Baseline extraction and positioned-clean-v2 (~10 min on 88 CPU workers); remove papers that overlap training windows.",
      "Score with each model to calibrate (current 4B and the new mix winner): ~15 min per model on 8 GPUs.",
      "Recompute thresholds with paper-level bootstrap intervals (flags cluster within papers; the current intervals treat sentences as independent and are too narrow).",
      "Update the Calibration page and the catalogue metadata."],
     ["2019–2022 topics differ from 2027; thresholds may still understate FPR on recent human writing."],
     "Thresholds from ≥1,500 papers with paper-clustered intervals; the document-level threshold no longer rests on 2 papers."),
    ("Decide whether AI-side text goes through the omission step",
     "This blocks using the cleaned human paper text in training.",
     "~15 min: choose the policy",
     "~3–4 h: 1–2 h implementation, ~1 h shortcut test on 2 GPUs, ~2 h CPU to regenerate the clean corpus",
     "Omissions v2 (math policy, references removal) is ready but not applied to the corpus",
     ["The problem: human paper text from PDFs contains ⟦… omitted⟧ markers; fully AI training documents (30% of windows) never do, so the model can learn 'marker means human'.",
      "Option A: remove markers from the input at training and inference. Simplest, no leak.",
      "Option B: keep markers, give their tokens an ignore label, and insert synthetic markers into fully AI documents at the human rate.",
      "Option C: render AI documents to PDF and extract them like human papers. Most faithful, most work.",
      "Recommendation: A now; consider C later for full AI manuscripts.",
      "Implement it in data.py and the inference preprocessing so the Atlas uses the same text; validate with the artifact-shortcut harness (marker present vs absent); regenerate the clean text with references removed."],
     ["Removing markers joins text across omitted regions; check that sentence boundaries stay correct."],
     "Policy recorded in AGENTS.md; the same preprocessing in training and inference; markers have no effect in the shortcut test."),
    ("Rotate the exposed HF and Jupyter tokens",
     "About 20 minutes, at a time when no running job depends on the old tokens.",
     "~20 min",
     "None",
     "Changing the Space's Jupyter token restarts the Space and clears /tmp, so do it when no runs are active",
     ["HF: huggingface.co → Settings → Access Tokens: create a token with the same scopes, run `hf auth login` on the Mac, then revoke the old token.",
      "Relaunch detached Space jobs that were started with the old HF token in their environment (persist daemon, uploads).",
      "Jupyter: change the Space secret, wait for the restart, update ~/.config/pangram/jupyter_token (mode 600)."],
     ["Revoking the HF token stops any job still using it."],
     "Old tokens revoked, new ones in place, dependent jobs relaunched."),
    ("Rescore ICLR 2027 with the chosen model and update the Atlas",
     "Uses the existing publish pipeline (bundled uploads).",
     "~15 min: approve the publish",
     "~1 day wall, mostly compute: scoring ~3.5 h on 8 A100s (4B), detail files ~1 h, upload ~5 min",
     "Item 1 (model), item 3 (calibration), item 4 (preprocessing); item 2 decides how results are described",
     ["Package the chosen checkpoint (merged LoRA, compiled) and benchmark it once.",
      "Score 42,419 papers with the 8-GPU claim queue, writing to /data.",
      "Compute sentence scores, flag rates and thresholds from the new human set.",
      "Build detail files from local copies (the bucket mount is slow) and upload with /bundle.",
      "Add the model to the catalogue next to Qwen3.5-4B · Experimental; extend the Calibration page to several models (~1–2 h).",
      "Rerun the year diagnostic with the new model."],
     ["A restart during the ~3.5 h scoring run: the claim queue resumes from /data."],
     "The new model is live on the Atlas with its own calibration section, and the year diagnostic has been rerun."),
]
