from pathlib import Path
import json,collections,datetime,hashlib
R=Path('/Users/alicerigg/codex-projects/pangram');O=Path(__file__).parent
load=lambda p:json.loads((R/p).read_text())
local=load('research/training-data-inventory/20261003/local-measurements.json');supp=load('research/training-data-inventory/20261003/local-supplement.json');space=load('research/training-data-inventory/20261003/space-datasets.json');hf=load('research/training-data-inventory/20261003/huggingface-repositories.json');derived=load('research/training-data-inventory/20261003/derived-counts.json')
remote={}
for fn in ['remote-measurements.jsonl','remote-supplement.jsonl']:
 for line in (O/fn).read_text().splitlines():
  d=json.loads(line)
  if 'source' in d:remote[d['source']]=d['data']
b='/data/workspace/paper-diversity-v1/'
counts=local['counts'];sources=[]
def add(id,name,rows,tokens,status,locations,notes,split_counts=None,token_method='sample estimate',parent=None):
 d=dict(id=id,name=name,rows=rows,tokens=tokens,token_method=token_method,status=status,locations=locations,notes=notes)
 if split_counts:d['splits']=split_counts
 if parent:d['parent']=parent
 sources.append(d);return d
human=56387707
add('human100k','Broad human source pool',100000,human,'User approved all passages for usage; final family/split preparation separate',['https://huggingface.co/datasets/open-text-detector/human-source-mix-v1','/data/workspace/human-source-mix-v2-recovered-20261002'],['34 sources; nine categories; latest HF revision da73a03fdfa863d5c44418e988d50137bcb53c47','Usage approval does not rewrite historical audit results or metadata fields. Original texts unchanged.','Former approved-collection.sqlite3 temporary path absent at audit; use approved HF release.'],token_method='exact saved count of unchanged text')
raw=remote['raw_mirrors_final_export']
add('mirrors30k','Luna synthetic mirrors raw',30000,raw['estimated_tokens'],'Complete raw collection; filtered subset recorded separately',['/data/workspace/synthetic-mirrors-luna-dollar-v1-recovered-20261002/raw-30000-20261002/checkpoints/00012-1790984912.tar.gz'],['Final archive streamed read-only and contained 30,000 export rows.','Full recovery of calls/per-document files uses all 12 incremental archives; final archive contains complete raw-documents.jsonl.','Do not add benchmark512, prior10k/20k exports or initial Luna-dollar outputs again.'],token_method='random 1000 of 30000, seed42')
add('mirrors28120','Luna mirrors accepted by automated checks',28120,None,'Recorded retained subset; temporary export absent; no durable filtered export found',['research/synthetic-mirrors/stage2-filter-report-20261002.json'],['1,880 rejected; raw30k preserved.','Acceptance is automated Stage2 checks, not completed semantic review or final family split.','Reproduce/check filtered output before training or publishing it; accepted-token count not inferred from raw average.'],parent='mirrors30k')
paragraphs=sum(v['estimated_tokens'] for v in counts['paper_10000_paragraphs'].values())
add('paper20k','Paper paragraph reconstruction pairs',20000,paragraphs,'Established train/validation/test split retained',['benchmarks/pangram4/exports/ai-paper-provenance-v3-10000','research/data/paper-gap10000-v3-luna-20260930','https://huggingface.co/datasets/woog/ai-paper-provenance-v3'],['10,000 generated target paragraphs plus10,000 matched human originals;2,000 papers.','Target-only token estimate. Context passage count is exactly8,063,003 stored reference tokens, includes repeated context.','Saved exact AI target-region tokens1,273,649. Historical eligibility flags retain6,375 passage rows/2,739 AI targets; eligibility is not equivalent to training split.','Fresh view excludes pilot exposures:11,700train/3,900validation/3,900test.'],{'train':12000,'validation':4000,'test':4000},'500 random target rows per split')
full=sum(v['estimated_tokens'] for v in counts['synthetic_full_papers']['models'].values())
add('full600','Synthetic full research manuscripts',600,full,'All finals included; train is storage convention, no leakage-controlled split',['research/data/synthetic-papers-600-hf-20261003','https://huggingface.co/datasets/open-text-detector/synthetic-research-papers-600'],['196 GPT-6.1-Sol,200 GPT-6-Sol,204 GPT-6-Luna, labeled by final revision model.','600unique final hashes and600unique source IDs. Title/abstract are human-supplied; generated body is AI. Do not label entire Markdown as pure AI token gold.','Includes synthetic methods/results; no experiments executed. Drafts/revisions/batch exports are copies or histories, not extra final documents.'],token_method='40 random manuscripts per final-model stratum,120 total')
for key,name in [('raid','RAID downloaded train none'),('mage','MAGE downloaded splits')]:
 paths=[b+'raid.csv'] if key=='raid' else [b+'mage-'+s+'.csv' for s in ['train','valid','test']]
 n=sum(remote[p]['rows'] for p in paths);t=sum(remote[p]['estimated_tokens'] for p in paths)
 audit=space['manifests'][b+'audit.json'];eligible=sum(audit['eligible_counts'][key].values())
 add(key,name,n,t,'Downloaded; only audited donor subset used in diversity experiments',paths,[f'Historical eligible donor pool: {eligible:,} rows; not additive to raw source.', 'RAID subset selects clean abstracts; MAGE subset selects human and topical/specified responses, excludes continuation setups and heldout overlap.','Do not treat all downloaded rows as approved train-ready data.'],{('train' if key=='raid' else p.split('mage-')[-1].split('.')[0]):remote[p]['rows'] for p in paths},'500 random rows per file')
paths=[b+'public-source-audit/gradtex-'+s+'.parquet' for s in ['train','validation','test']]
add('gradtex','GRADTEX',sum(remote[p]['rows'] for p in paths),sum(remote[p]['estimated_tokens'] for p in paths),'Accepted by user as-is for current Stage3 plan',paths,['User explicitly requested no further deep review.','79,065train rows comprise39,532human and39,533AI-involved; upstream binary1=human,0=AI-involved.','Derived from MAGE, with overlapping source material. Document/scenario labels do not establish token gold.','Existing historical length/overlap-filtered donor pool68,647 is a derivative, not additional data or a new restriction on user acceptance.'],{p.split('gradtex-')[-1].split('.')[0]:remote[p]['rows'] for p in paths},'500 random rows per split')
paths=[p for p in remote if '/seqxgpt-original/' in p]
elig=remote[b+'public-source-audit/pilot-preparation-status.json']['spec']['eligible_pool']
add('seqxgpt','SeqXGPT original English files',sum(remote[p]['rows'] for p in paths),sum(remote[p]['estimated_tokens'] for p in paths),'Prepared mixed-provenance training donor subset exists',paths,[f'6,000human plus29,904generated/continuation records across5generators. Current prepared eligible pool{sum(elig.values()):,}.','Group split:28,730train/3,326validation/3,680test/168excluded; subsequent donor checks further narrow training pool.','Retain human prefix versus generated suffix boundary semantics; do not label prefixes AI.'],{'train_candidates':28730,'validation':3326,'test':3680,'excluded':168},'500 random rows per generator file')
p=b+'public-source-audit/hip-audit/train.parquet'
add('hip','HIP human and paraphrase pairs',10581,remote[p]['estimated_tokens']+remote[p+'#paraphrases']['estimated_tokens'],'Set aside by user; preserve files',[p,b+'public-source-audit/hip-audit/pair-preparation-grouped-v2'],['10,581pairs =21,162text sides, derived from MAGE/RAID; do not add originals again to those sources.','Prepared grouped subset5,862train/697selection/766reserved-test pairs; native test prefix samples256AI+256human.','No per-token provenance supplied for paraphrases.'],token_method='500 random pairs; both text fields counted')
base='/data/workspace/open-pangram-private-copy/dataset/'
paths=[p for p in remote if p.startswith(base+'editlens_iclr/')]
add('editlens','EditLens ICLR',sum(remote[p]['rows'] for p in paths),sum(remote[p]['estimated_tokens'] for p in paths),'Existing private copied dataset; original split semantics retained',[base+'editlens_iclr','https://huggingface.co/datasets/open-text-detector/editlens_iclr'],['Human, AI-generated and AI-edited document labels; source_text and similarity scores are metadata, not automatically gold token labels.','Test_llama and test contain related human sources; totals are stored rows, not globally independent documents.'],{p.split('/')[-1].split('-00000')[0]:remote[p]['rows'] for p in paths},'500 random rows per split')
p=base+'editlens_iclr_grammarly/data/train-00000-of-00001.parquet'
add('grammarly','EditLens Grammarly edits',1768,remote[p]['estimated_tokens'],'Existing private copied editing dataset',[p,'https://huggingface.co/datasets/open-text-detector/editlens_iclr_grammarly'],['Original source_text, edit_instructions and edited text retained. Count covers edited text only.','train filename is not evidence of completed project admission or token-label preparation.'],{'train':1768},'500 random edited texts')
add('arena','Arena multi-model responses',5000,3699370,'Development-exposed evaluation; future training needs prompt-group split',['benchmarks/pangram4/exports/arena-prose-100-49-models','https://huggingface.co/datasets/woog/arena-prose-100-49-models'],['100prompts ×50models;4,898mechanically eligible. The49-model folder name is stale.','Earlier Arena20/100/cheap/skipped/Kimi exports contain responses reused in the current package; do not sum them. Additional historical outputs were not globally reconciled.'],{'test':5000},'500 random responses')
add('workflow','Paper workflow evaluation',1323,None,'Evaluation-only; original assignments retained',['research/data/paper-eval-workflows-luna-20260930','https://huggingface.co/datasets/woog/ai-paper-workflow-eval'],['189papers:27pilot/54calibration/108test.','756reconstruction targets +567assistance outputs;2,646correlated views +378matched-human views.','9,301body paragraphs,1,590clean/novel human paragraphs are related controls, not independent generated documents.','567editing outputs remain eval-only; cancelled half-split proposal must not be applied.','Token estimate omitted because correlated full/context/target views have different counting units.'])
for key,name in [('human_pg19','PG19 historical books'),('ai_mdta_2025','MDTA selected 2025 responses')]:
 d=counts[key];add(key,name,d['rows'],d['estimated_tokens'],'Legacy evaluation/source pool',[f'research/data/{key}'],['Already used in benchmark controls/proxies; no new training assignment inferred.'],token_method=d['count_method'])
add('paper_archive','Canonical extracted paper archive',14561,supp['paper_archive_estimate']['estimated_tokens'],'Unlabeled source archive, not human-authorship gold',['research/exports/paper-text-hf','https://huggingface.co/datasets/woog/pangram-paper-text'],['train split is storage convention. Includes overlap with research/paper datasets and extractions.','Paper year or full text does not establish human-only authorship.'],token_method='100 random papers; large-length variance')
add('reviewbench','ReviewBench source papers and reviews',51529,None,'Source corpus, no detector-training labels',['research/data/reviewbench/original','research/data/reviewbench/catalogue.sqlite3'],['51,453rows have nonempty manuscript Markdown;15downloaded Parquet shards.','Contains paper metadata/reviews/manuscripts; overlaps source paper archive and paper-generation seeds.','Total corpus tokens unmeasured; no corpus-wide model/token pass performed.'])
add('iclr_controls','ICLR 2023 and 2026 controls',200,counts['iclr_2023']['estimated_tokens']+counts['iclr_2026']['estimated_tokens'],'Legacy controls; year is not authorship label',['research/data/iclr_2023','research/data/iclr_2026'],['100papers per cohort; caches and archive may overlap.'],token_method='exact stored-text count,200 rows')
add('qwen_pilot','Qwen3.5 mirror pilot',10,None,'Historical development pilot;9mechanical passes,0admitted',['/data/workspace/synthetic-mirrors-v1/pilot/mirrors.jsonl'],['Separate from the Luna-only30,000collection. Qwen3.5-4B BF16 generation; completed10of10.','Preserved pilot; no expansion or training use inferred.'])
# All 34 source rows, mapped to finalized human counts and current raw-mirror counts.
plan=load('research/human-source-pool/sampling-plan.json');dist=load('research/human-source-pool/original-distribution-report.json');cats={r['source_id']:r['category'] for r in plan['source_quotas']}
human_sources=[dict(source_id=r['source_id'],category=cats[r['source_id']],human_passages=r['actual'],raw_synthetic_documents=raw['sources'].get(r['source_id'],0)) for r in dist['sources'] if r['actual']>0]
assert sum(r['human_passages'] for r in human_sources)==100000 and sum(r['raw_synthetic_documents'] for r in human_sources)==30000
inventory={'audit_date':'2026-10-03','timezone':'America/Los_Angeles','tokenizer_sha256':local['tokenizer_sha256'],'sources':sources,'human_source_breakdown':human_sources,'evaluation_prepared':local['prepared_benchmarks'],'evaluation_source_eligible_counts':{k:v.get('eligible') for k,v in load('benchmarks/pangram4/data/prepared/manifest.json')['datasets'].items()},'historical_paper_runs':local['historical_paper_runs'],'historical_exact_overlap':supp['historical_exact_overlap'],'hf_repositories':[{'id':x['id'],'revision':x['sha'],'private':x['private']} for x in hf['repositories']],'custom_primary_gross_tokens_estimate':human+raw['estimated_tokens']+paragraphs+full,'custom_primary_rows':150600,'no_global_deduplicated_training_total':True,'limitations':['No cross-corpus near-deduplication or new split/admission decisions performed.','Repository-local datasets, known Space workspace, project HF namespaces, and shallow own-directory shared-server check covered; inaccessible/deeper unrelated account storage not claimed.','Filtered synthetic export absent at recorded temporary path and not found in searched persistent mirror/stage4 locations.','Counts and estimates use stored text; do not include prompts, hidden reasoning, padding, repeated epochs or model weights.']}
(O/'inventory.json').write_text(json.dumps(inventory,indent=2)+'\n')
# Human-readable report.
def m(n):return 'Not measured' if n is None else f'{n/1e6:,.2f}M'
def link(path):return f'[{path}](../{path})' if not path.startswith(('/', 'https://')) else f'`{path}`'
lines=['# Training data inventory','', 'Audited October 3, 2026, Pacific time. This inventory covers local project files, live Hugging Face training-Space storage, the project’s Hugging Face dataset repositories, and a shallow search of the user’s own directory on the shared server. It records what exists, which versions overlap, where the data live, and what is actually assigned to training. It does not launch generation, train models, change splits, or upload datasets.','',f'**The four main custom collections contain about {inventory["custom_primary_gross_tokens_estimate"]/1e6:.1f} million stored-text tokens across 150,600 records:** 100,000 human passages, 30,000 raw mirrors, 20,000 paper target paragraphs, and 600 full manuscripts. This is a gross inventory estimate, not a deduplicated or training-ready total. The 28,120 accepted mirrors are a subset of the 30,000, and the paper collection includes held-out splits. Larger public corpora and unlabeled paper archives are listed separately.','', '## Changes since the earlier count','', '- The new **600 full manuscripts add about 4.43M tokens**, including their human-supplied title/abstract sections. Final revision models: 196 GPT-6.1-Sol, 200 GPT-6-Sol, 204 GPT-6-Luna. All 600 finals are present in the consolidated local package and private HF release.', '- **Human usage approval now covers all 100,000 passages.** The latest published revision includes that approval. Earlier zero-admission/audit fields remain historical evidence; they do not negate the user’s later usage decision.', '- **Mirrors finished at 30,000 raw documents**, approximately 15.65M tokens. Later automated checks retained **28,120** and rejected **1,880**. These accepted records still need final family/split preparation.', '- **Arena now contains 5,000 responses from 50 models**, not 4,900/49. The repository and local folder names retain the old number.', '- GRADTEX is accepted as-is for the current plan. HIP is set aside. The proposed half/half paper split and its trial arms were cancelled.','', '## Current custom collections','', '| Collection | Records | Text tokens | Current use |','|---|---:|---:|---|']
for id in ['human100k','mirrors30k','mirrors28120','paper20k','full600']:
 d=next(x for x in sources if x['id']==id);lines.append(f'| {d["name"]} | {d["rows"]:,} | {m(d["tokens"])} | {d["status"]} |')
lines+=['','The 20,000 paragraph rows are **10,000 AI targets plus 10,000 human originals**, not 20,000 AI generations. Preserve 12,000 train / 4,000 validation / 4,000 test. The target-only view is approximately 2.59M tokens; the context-preserving passage view contains exactly 8,063,003 reference tokens, including repeated surrounding human text. These are alternate views, not additive datasets. Only the training target view is about 1.57M tokens.','', 'The current backbone-prepared training table is a derivative: **26,731 rows = 3,146 paired + 23,585 novel-human rows**. Selection has 4,459 rows and calibration 4,484. Its 6,000 stage-1 and three 12,000 stage-2 draw lists are repeated training exposure, not extra unique data. Quality filtering and novel-body extraction mean this derivative is not identical to the entire 12,000-row original training split.','', '## Downloaded public and copied editing corpora','', '| Collection | Stored records | Approximate text tokens | Split or prepared subset |','|---|---:|---:|---|']
for id in ['raid','mage','gradtex','seqxgpt','hip','editlens','grammarly']:
 d=next(x for x in sources if x['id']==id);sp=', '.join(f'{k}: {v:,}' for k,v in d.get('splits',{}).items()) or ('10,581 human/paraphrase pairs; set aside' if id=='hip' else 'See source details')
 lines.append(f'| {d["name"]} | {d["rows"]:,} | {m(d["tokens"])} | {sp} |')
audit=space['manifests'][b+'audit.json']
lines+=['',f'Historical audited donor pools: **RAID {sum(audit["eligible_counts"]["raid"].values()):,}**, **MAGE {sum(audit["eligible_counts"]["mage"].values()):,}**, **GRADTEX 68,647**, and **SeqXGPT {sum(elig.values()):,}**. These pools are contained in their source downloads. GRADTEX derives from MAGE; HIP derives from MAGE and RAID. Summing their raw rows/tokens would count related source material repeatedly.','', 'GRADTEX’s training split has 39,532 human and 39,533 AI-involved rows. Its native binary label uses 1 for human and 0 for AI-involved. Editing/scenario/document labels are not token-span gold. The historical 68,647-row donor preparation imposed experiment-specific length/overlap filters; it does not override the user’s later as-is acceptance. HIP remains excluded from the current plan despite retained prepared files.','', '## Evaluation and source-only collections','', '| Collection | Size | Role |','|---|---:|---|','| Arena | 5,000 responses, 100 prompts, 50 models | Development-exposed test; 4,898 mechanically eligible; prompt-group split required before any training reuse |','| Paper workflows | 1,323 distinct outputs from 189 papers | 756 reconstructions + 567 edits; pilot/calibration/test only; 2,646 correlated views |','| Workflow human controls | 9,301 body paragraphs; 1,590 clean/novel | Controls related to those 189 papers, not new independent paper sources |','| PG19 | 100 full books; 10.30M stored tokens | Downloaded test split; legacy human controls and excerpt proxies |','| MDTA 2025 subset | 6,397 responses; about 1.30M tokens | Legacy AI evaluation, two generator families |','| Canonical extracted paper archive | 14,561 papers; about 423M tokens | Unlabeled source text, overlapping paper datasets; train filename is a storage convention |','| ReviewBench | 51,529 records; 51,453 with manuscript Markdown | 15 downloaded shards with manuscripts/reviews/metadata; no detector authorship gold |','| ICLR year controls | 100 from 2023 + 100 from 2026; 4.71M stored tokens | Historical controls; publication year does not prove human authorship |','| OpenReview catalogues and abstract seed sets | Metadata and 600 selected title/abstract seeds | Source discovery and generation inputs, not extra synthetic documents |','', 'The frozen detector suite packages overlapping profiles: comparison 13,751 rows, workflow 8,552, assistance 972, full 65,348, plus contextual controls and separate validation files. Do not add those profiles to each other or to their source data. Prepared benchmark subsets currently on disk are:','', '| Prepared source | Rows | Exact unique texts within file | Source eligible pool in saved importer manifest |','|---|---:|---:|---:|']
for name,d in local['prepared_benchmarks'].items():lines.append(f'| {name} | {d["rows"]:,} | {d["unique_texts"]:,} | {inventory["evaluation_source_eligible_counts"].get(name) or "Not recorded"} |')
lines+=['','These prepared counts are bounded evaluation selections, not total upstream dataset sizes. Sources include DetectRL, ELLIPSE, Epoch, GEDE, Liang, MELD-eval, OpAI, PELIC, Perkins, Saha, Sem-Detect and VUB. Their publisher receipts and selection rules are in [benchmark coverage](../benchmarks/pangram4/COVERAGE.md); retained native labels are not automatically token labels.','', '## Source breakdown for the broad human pool and mirrors','', 'Human counts come from the final 100,000-row distribution report; mirror counts were read from the recovered final 30,000-row export. Accepted-mirror counts are available by category, not source, in the saved filter report.','', '| Source | Category | Human passages | Raw mirrors |','|---|---|---:|---:|']
for row in human_sources:lines.append(f'| {row["source_id"]} | {row["category"]} | {row["human_passages"]:,} | {row["raw_synthetic_documents"]:,} |')
lines+=['| **Total** | | **100,000** | **30,000** |','', 'The planned ELLIPSE contribution to this pool is zero; the separate2,571-essay ELLIPSE evaluation set is preserved. All 34 nonempty human-source groups have user usage approval. Preserve their origin/permission audit findings, source attribution, and existing protected-family metadata; usage approval and a completed leakage-controlled split are different records. No multilingual collection was added.','', '## Copies and historical versions','', '- The v3 250-pair pilot and 2,500-pair expansion are wholly contained in the final 10,000-pair paper corpus by exact passage-text hashes: 500/500 and 5,000/5,000 rows respectively. The old `ai-paper-provenance-v3` export is a smaller view/version, not an additional 5,000 rows.', '- Other 50/250-target v1/v2/v4 pilots and the 10/50-paper editing pilots contain additional historical outputs, but are development-exposed and share sources. They are documented below and excluded from the main custom total; their rows are not independent new paper families.', '- A separate Qwen3.5-4B mirror pilot contains10outputs,9mechanical passes and0admitted; it is preserved outside the Luna30k total.', '- Original Arena20, Arena100, cheap, skipped and Kimi runs contain responses reused by the final 5,000-response package. Parquet/JSONL/ZIP copies, manuscript drafts/revisions, detector predictions, API attempt logs, epoch draw lists and storage snapshots are not added to the corpus total.', '- Human-pool v1/v2/recovery checkpoints and HF releases describe stages or copies of the same current 100,000-passage collection. Earlier Luna-dollar mirror runs and the 512-output throughput benchmark are already included in the 30,000 raw mirrors.','', '| Historical local paper run | Stored rows | Rows exactly present in current 20,000 | Unique passages outside current version |','|---|---:|---:|---:|']
for path,d in supp['historical_exact_overlap'].items():lines.append(f'| `{Path(path).name}` | {d["rows"]:,} | {d["rows_exactly_in_current_20000"]:,} | {d["unique_passages_not_in_current"]:,} |')
lines+=['','“Outside current version” is only an exact-text comparison with that corpus, not cross-pilot deduplication or approval for training.','', '## Storage and upload status','', '**Recovery issue:** the recorded `/tmp/pangram-human-active-20261002` and `/tmp/pangram-luna-active-20261002` working folders are absent on the current Space. Persistent `/data/workspace` is readable again. The latest human HF release is intact at the same recorded revision; the complete 30,000-row raw mirror export was streamed successfully from the final persistent archive. The filtered `accepted.jsonl` was historically not uploaded, and no copy was found in the searched persistent mirror/stage4 folders. Its 28,120-row count and checksums survive locally, but the file must be recovered or reproduced and verified before use. This inventory did not rerun filtering or change any data.','', '| Data | Current destination | Upload action in this audit |','|---|---|---|','| Human100k | Private `open-text-detector/human-source-mix-v1` | Already published; current revision verified by metadata |','| Full manuscripts600 | Private `open-text-detector/synthetic-research-papers-600` | Already published; current revision verified by metadata |','| Paper20k, Arena5k, workflow evaluation | Existing `woog` dataset releases | Already published; current revision verified by metadata |','| EditLens + Grammarly | Existing private `open-text-detector` dataset copies | Already published and present on Space |','| Raw mirrors30k | Private training-storage bucket, mounted under `/data/workspace/.../raw-30000-20261002/checkpoints` | Already backed up; export read during this audit |','| Accepted mirrors28,120 | Historical temporary export absent | Main future upload candidate after recovery/reproduction; no upload launched |','| RAID/MAGE/GRADTEX/SeqXGPT/HIP | Existing Space dataset files | No new publication planned |','', 'Standing approval recorded October 3 in [AGENTS.md](../AGENTS.md) now allows all data transfers **to the existing training Space**. It does not itself schedule uploads, change dataset-sharing permissions, or authorize other destinations.','', '## Canonical source locations and decisions','']
for d in sources:
 lines += [f'### {d["name"]}','',d['status']+'.','']
 for loc in d['locations']:lines.append('- '+(f'[{loc}](../{loc})' if not loc.startswith(('/', 'https://')) else f'[{loc}]({loc})' if loc.startswith('https://') else '`'+loc+'`'))
 lines+=['']+[f'- {n}' for n in d['notes']]+['']
lines+=['## Measurement method and evidence','', 'Token estimates use the same existing MELD-v8/ModernBERT tokenizer on both machines (SHA256 `6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30`). Text is counted without special tokens, truncation or padding. No inference, model downloads, paid generation, or full-dataset tokenization was performed for the large remote corpora. Exact stored counts are reused where available. Most estimates tokenize 500 uniformly sampled rows per file; raw mirrors use 1,000; full manuscripts use 40 per final-model group; the unlabeled paper archive uses 100. Random seed42 and sample uncertainty are recorded in the evidence. Small local100-row control files were counted in full.','', 'The approximate 79.1M custom subtotal is human text + raw mirror text + target-only paper paragraphs + final full-manuscript Markdown. It includes held-out rows, raw rejected outputs and human seed text, and excludes evaluation collections, public corpora, older distinct pilots and the unlabeled archive. It must not be reported as a unique trainable-token count. A global training total requires chosen splits, text views, provenance labels and cross-source grouping/deduplication; those were not changed by this inventory.','', 'Live checks were read-only except for documentation and the requested project-rule update. HF checks verified repository revisions and file metadata, not a new full byte readback of every remote dataset. The shared-server check found no matching dataset files within three levels of `/workspace/home/woog`, excluding GPU-monitor data and caches; it is not a scan of other tenants or every remote directory. Hjarni searches returned no relevant project notes.','', '- [Machine-readable inventory](training-data-inventory/20261003/inventory.json)', '- [Local estimates and historical counts](training-data-inventory/20261003/local-measurements.json)', '- [Remote dataset estimates](training-data-inventory/20261003/remote-measurements.jsonl)', '- [Remote MAGE and prepared-training details](training-data-inventory/20261003/remote-supplement.jsonl)', '- [Space storage and schemas](training-data-inventory/20261003/space-datasets.json)', '- [HF repositories and file metadata](training-data-inventory/20261003/huggingface-repositories.json)', '- [Local directories searched](training-data-inventory/20261003/local-directory-census.json)', '- [Historical exact-overlap and archive measurements](training-data-inventory/20261003/local-supplement.json)', '- [Human usage approval](human-source-pool/origin-permission-audit/user-usage-approval-receipt.json)', '- [Mirror filtering report](synthetic-mirrors/stage2-filter-report-20261002.json)', '- [Current Stage3 decision](stage3-edits/decision.json)', '']
report='\n'.join(lines)
for old,new in {
 '10,000generated':'10,000 generated','10,000matched':'10,000 matched','10,000human':'10,000 human','2,000papers':'2,000 papers',
 'generation inputs':'generation inputs','1,273,649.':'1,273,649.',
 '6,375 passage rows/2,739 AI targets':'6,375 passage rows / 2,739 AI targets',
 '11,700train/3,900validation/3,900test':'11,700 train / 3,900 validation / 3,900 test',
 '196 GPT-6.1-Sol,200 GPT-6-Sol,204 GPT-6-Luna':'196 GPT-6.1-Sol, 200 GPT-6-Sol, 204 GPT-6-Luna',
 '600unique':'600 unique','39,532human':'39,532 human','39,533AI-involved':'39,533 AI-involved',
 'binary1=human,0=AI-involved':'binary 1 = human, 0 = AI-involved','pool68,647':'pool 68,647',
 '6,000human plus29,904generated/continuation records across5generators':'6,000 human plus 29,904 generated/continuation records across 5 generators',
 'pool26,517':'pool 26,517','28,730train/3,326validation/3,680test/168excluded':'28,730 train / 3,326 validation / 3,680 test / 168 excluded',
 '10,581pairs =21,162text sides':'10,581 pairs = 21,162 text sides',
 'subset5,862train/697selection/766reserved-test':'subset 5,862 train / 697 selection / 766 reserved-test',
 'samples256AI+256human':'samples 256 AI + 256 human',
 '100prompts ×50models;4,898mechanically':'100 prompts × 50 models; 4,898 mechanically',
 'The49-model':'The 49-model','189papers:27pilot/54calibration/108test':'189 papers: 27 pilot / 54 calibration / 108 test',
 '756reconstruction targets +567assistance outputs;2,646correlated views +378matched-human views':'756 reconstruction targets + 567 assistance outputs; 2,646 correlated views + 378 matched-human views',
 '9,301body paragraphs,1,590clean/novel':'9,301 body paragraphs, 1,590 clean/novel',
 '567editing':'567 editing','15downloaded':'15 downloaded','100papers':'100 papers',
 'Luna-only30,000collection':'Luna-only 30,000 collection','completed10of10':'completed 10 of 10',
 'pilot;9mechanical passes,0admitted':'pilot; 9 mechanical passes, 0 admitted',
 'contains10outputs,9mechanical passes and0admitted':'contains 10 outputs, 9 mechanical passes and 0 admitted',
 'Luna30k':'Luna 30k','separate2,571-essay':'separate 2,571-essay',
 'Stage2':'Stage 2','Stage3':'Stage 3','seed42':'seed 42','local100-row':'local 100-row',
 'benchmark512':'benchmark 512','prior10k/20k':'prior 10k/20k','raw30k':'raw 30k',
 'Human100k':'Human 100k','manuscripts600':'manuscripts 600','Paper20k':'Paper 20k','Arena5k':'Arena 5k','mirrors30k':'mirrors 30k','mirrors28,120':'mirrors 28,120',
}.items():report=report.replace(old,new)
(R/'research/TRAINING_DATA_INVENTORY.md').write_text(report)
print(json.dumps({'sources':len(sources),'human_sources':len(human_sources),'custom_gross_tokens':inventory['custom_primary_gross_tokens_estimate'],'report':'research/TRAINING_DATA_INVENTORY.md'}))

# Apply subsequent verified transfers when their completion receipt is present.
from reconcile_publication import reconcile
reconcile()
