"""Paper-disjoint inference study: prompt/context variants, monotone calibration and CV.

No teacher text, scores, year, or venue enters Laya's input. Model weights are fixed.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from pangram_backend.providers.laya import INSTRUCTION, OPTIONS, Laya

OUT = ROOT / "research/benchmarks/laya-meld-v8"
VARIANTS = {
    "baseline": {
        "instruction": INSTRUCTION,
        "options": OPTIONS,
        "max_length": 512,
        "context": True,
    },
    "concise_context": {
        "instruction": "Who wrote TARGET PHRASE? Use CONTEXT BEFORE and CONTEXT AFTER to interpret it, but classify only TARGET PHRASE.",
        "options": [
            "human: A person wrote the text.",
            "ai: An AI language model wrote the text.",
        ],
        "max_length": 512,
        "context": True,
    },
    "concise_local": {
        "instruction": "Who wrote TARGET PHRASE? Use CONTEXT BEFORE and CONTEXT AFTER to interpret it, but classify only TARGET PHRASE.",
        "options": [
            "human: A person wrote the text.",
            "ai: An AI language model wrote the text.",
        ],
        "max_length": 256,
        "context": True,
    },
    "isolated_authorship": {
        "instruction": "Classify the authorship of the following text.",
        "options": [
            "human: Written by a human author.",
            "ai: Generated or substantially rewritten by an AI language model.",
        ],
        "max_length": 512,
        "context": False,
    },
    "style_evidence": {
        "instruction": "Assess TARGET PHRASE for evidence of AI-generated or AI-rewritten writing. Use the surrounding context. Scientific subject matter, technical terminology and formal writing alone are not evidence of AI use.",
        "options": [
            "human: Natural human-authored prose; no clear evidence of language-model generation.",
            "ai: Language-model-generated prose or substantial language-model rewriting.",
        ],
        "max_length": 512,
        "context": True,
    },
    "direct_detection": {
        "instruction": "Is TARGET PHRASE AI-generated? Judge only the target, using surrounding text as context.",
        "options": [
            "no: The text was written by a human.",
            "yes: The text was generated by artificial intelligence.",
        ],
        "max_length": 512,
        "context": True,
    },
    "chatgpt_local": {
        "instruction": "Was TARGET PHRASE written by a human researcher or generated by ChatGPT? Use nearby text for context.",
        "options": [
            "human: Human-written scientific text.",
            "chatgpt: ChatGPT-generated scientific text.",
        ],
        "max_length": 256,
        "context": True,
    },
    "style_local": {
        "instruction": "Which writing style better describes TARGET PHRASE? Use the surrounding context.",
        "options": [
            "human: Specific, varied, idiosyncratic human scientific prose.",
            "ai: Formulaic, uniformly polished, generic explanatory prose characteristic of a language model.",
        ],
        "max_length": 256,
        "context": True,
    },
    "reversed_choices": {
        "instruction": INSTRUCTION,
        "options": list(reversed(OPTIONS)),
        "max_length": 512,
        "context": True,
        "reverse": True,
    },
}


def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -40, 40)))


def logit(p):
    p = np.clip(p, 1e-6, 1 - 1e-6)
    return np.log(p / (1 - p))


def rank(x):
    _, inverse, counts = np.unique(x, return_inverse=True, return_counts=True)
    return (np.cumsum(counts) - (counts + 1) / 2)[inverse]


def correlation(x, y):
    if np.std(x) < 1e-12 or np.std(y) < 1e-12:
        return 0.0
    return float(np.corrcoef(x, y)[0, 1])


def metrics(pred, target, paper_ids):
    pred, target = np.asarray(pred), np.asarray(target)

    def color(x):
        return (x > 0.2).astype(int) + (x > 0.8).astype(int)

    pc, tc = color(pred), color(target)
    local = [
        correlation(rank(pred[paper_ids == p]), rank(target[paper_ids == p]))
        for p in np.unique(paper_ids)
    ]
    pos = target >= 0.5
    auc = (
        float(
            (rank(pred)[pos].sum() - pos.sum() * (pos.sum() - 1) / 2)
            / (pos.sum() * (~pos).sum())
        )
        if pos.any() and (~pos).any()
        else None
    )
    return {
        "mae": float(np.mean(abs(pred - target))),
        "rmse": float(np.sqrt(np.mean((pred - target) ** 2))),
        "spearman": correlation(rank(pred), rank(target)),
        "mean_within_paper_spearman": float(np.mean(local)),
        "pearson": correlation(pred, target),
        "color_accuracy": float(np.mean(pc == tc)),
        "balanced_color_accuracy": float(
            np.mean([np.mean(pc[tc == c] == c) for c in np.unique(tc)])
        ),
        "auc_meld_above_half": auc,
        "count": len(pred),
    }


def fit_calibration(x, y):
    # Two-parameter monotone map, optimized on squared score error; no per-paper intercepts.
    best = (float("inf"), 0.0, 0.0)
    for step in [1.0, 0.2, 0.04]:
        slopes = (
            np.arange(0, 6.01, 0.25)
            if step == 1
            else np.arange(
                max(0, best[1] - step * 2), best[1] + step * 2 + step / 2, step / 2
            )
        )
        offsets = (
            np.arange(-6, 6.01, 0.1)
            if step == 1
            else np.arange(best[2] - step * 2, best[2] + step * 2 + step / 2, step / 2)
        )
        for a in slopes:
            losses = np.mean(
                (sigmoid(a * x[:, None] + offsets[None, :]) - y[:, None]) ** 2, axis=0
            )
            j = int(losses.argmin())
            if losses[j] < best[0]:
                best = (float(losses[j]), float(a), float(offsets[j]))
    return {"slope": best[1], "intercept": best[2]}


def calibrate(x, fit):
    return sigmoid(fit["slope"] * x + fit["intercept"])


def build_rows(provider, paper, indices, variant):
    import re

    enc = provider._encode
    t = provider.tokenizer
    prefix = (
        [t.cls_token_id]
        + enc("choice question: " + variant["instruction"])
        + [t.sep_token_id]
    )
    markers = []
    for option in variant["options"]:
        markers.append(len(prefix))
        prefix += [t.mask_token_id] + enc(" " + option)[:48]
    prefix += [t.sep_token_id]
    labels = [
        enc(s)
        for s in ("CONTEXT BEFORE:\n", "\nTARGET PHRASE:\n", "\nCONTEXT AFTER:\n")
    ]
    text = paper["text"]
    rows = []
    for index in indices:
        row = paper["rows"][index]
        start, end = row["start"], row["end"]
        target = enc(text[start:end])
        if variant["context"]:
            budget = (
                variant["max_length"]
                - len(prefix)
                - sum(map(len, labels))
                - len(target)
                - 1
            )
            if budget < 0:
                raise ValueError("Target truncation forbidden")
            before = enc(re.split(r"\n\s*\n", text[max(0, start - 4096) : start])[-1])
            after = enc(re.split(r"\n\s*\n", text[end : end + 4096])[0])
            nl = min(len(before), budget // 2)
            nr = min(len(after), budget - nl)
            nl = min(len(before), budget - nr)
            state = (
                labels[0]
                + (before[-nl:] if nl else [])
                + labels[1]
                + target
                + labels[2]
                + after[:nr]
            )
        else:
            state = target
        ids = prefix + state + [t.sep_token_id]
        if len(ids) > variant["max_length"]:
            raise ValueError("Input too long")
        rows.append(dict(row, ids=ids))
    return rows, markers


def predict(provider, paper, indices, variant):
    rows, markers = build_rows(provider, paper, indices, variant)
    provider.markers = markers
    values = np.array(provider.score_rows(rows))
    return (1 - values if variant.get("reverse") else values).tolist()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variants", default=",".join(VARIANTS))
    args = ap.parse_args()
    manifest = json.loads((OUT / "manifest.json").read_text())
    papers = [
        json.loads((OUT / (m["pdf_sha256"] + ".json")).read_text())
        for m in manifest["papers"]
        if m["split"] == "development"
    ]
    p = Laya(
        model_dir=ROOT / "models", runtime="mlx", precision="float16", batch_size=4
    )
    p._load()
    predictions = OUT / "screen"
    predictions.mkdir(exist_ok=True)
    for name in args.variants.split(","):
        config = VARIANTS[name]
        for paper in papers:
            pdf = paper["paper"]["pdf_sha256"]
            dest = predictions / (name + "-" + pdf + ".json")
            if dest.exists():
                continue
            begin = time.perf_counter()
            indices = paper["paper"]["screen_indices"]
            values = predict(p, paper, indices, config)
            dest.write_text(
                json.dumps(
                    {
                        "variant": name,
                        "config": config,
                        "pdf_sha256": pdf,
                        "indices": indices,
                        "scores": values,
                        "seconds": time.perf_counter() - begin,
                    }
                )
            )
        print(json.dumps({"variant_completed": name}), flush=True)
        summarize(manifest, papers)
    summarize(manifest, papers)


def summarize(manifest, papers):
    target = np.array(
        [
            r["rows"][i]["teacher_score"]
            for r in papers
            for i in r["paper"]["screen_indices"]
        ]
    )
    ids = np.array(
        [j for j, r in enumerate(papers) for i in r["paper"]["screen_indices"]]
    )
    candidates = {}
    for name in VARIANTS:
        paths = [
            OUT / "screen" / (name + "-" + r["paper"]["pdf_sha256"] + ".json")
            for r in papers
        ]
        if not all(f.exists() for f in paths):
            continue
        values = np.array(
            [v for f in paths for v in json.loads(f.read_text())["scores"]]
        )
        candidates[name] = values
    if "baseline" in candidates and "reversed_choices" in candidates:
        candidates["order_ensemble"] = sigmoid(
            (logit(candidates["baseline"]) + logit(candidates["reversed_choices"])) / 2
        )
    results = {}
    for name, values in candidates.items():
        x = logit(values)
        cv = np.zeros(len(x))
        for fold in range(4):
            train = ids % 4 != fold
            test = ~train
            cv[test] = calibrate(x[test], fit_calibration(x[train], target[train]))
        results[name] = {
            "raw": metrics(values, target, ids),
            "paper_disjoint_cv": metrics(cv, target, ids),
            "calibration": fit_calibration(x, target),
        }
    constant = np.zeros(len(target))
    for fold in range(4):
        constant[ids % 4 == fold] = target[ids % 4 != fold].mean()
    report = {
        "split": "development_only",
        "folds": "four folds by paper; no phrase overlap across folds",
        "constant_cv_baseline": metrics(constant, target, ids),
        "variants": results,
    }
    (OUT / "development-results.json").write_text(json.dumps(report, indent=2))
    print(
        json.dumps(
            {
                k: {
                    "raw_mae": v["raw"]["mae"],
                    "cv_mae": v["paper_disjoint_cv"]["mae"],
                    "rank": v["raw"]["spearman"],
                    "within_paper_rank": v["raw"]["mean_within_paper_spearman"],
                }
                for k, v in results.items()
            }
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
